import expandedFamilies from './expanded-families.json';
import productSalesCopy from './product-sales-copy.json';
import {productCopy} from './content';
import {industryStories} from './industry-stories';
export const brand = 'Parknonwoven EPP';
export const origin = process.env.NEXT_PUBLIC_SITE_URL || 'https://park-epp.vercel.app';
export const slugify = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
/** Original application records retained for product data and existing detail URLs. */
export const legacyMarkets = [
 {name:'HVAC', intro:'Bring insulation, air management and assembly into a more considered component design.', need:'Airflow geometry, thermal interfaces, acoustic behaviour and access for servicing belong in the same design brief.', products:['Custom HVAC components','Moulded air ducts','HVAC insulation housings'], image:'technical'},
 {name:'Aviation', intro:'Explore lightweight interior components around demanding installation and validation requirements.', need:'Start with the aircraft application, applicable fire requirements, traceability and the approval process before selecting a polymer.', products:['Aircraft interior components','Lightweight aviation inserts'], image:'technical'},
 {name:'Furniture', intro:'Shape comfortable furniture and protect finished surfaces through storage and delivery.', need:'Balance feel, shape retention, upholstery interfaces and transport protection against the intended use and service life.', products:['Protective furniture foams','Corner protectors','EPP foam sheets','Foam furniture'], image:'technical'},
 {name:'Mobility', intro:'Use material and geometry together to rethink the weight of vehicle components.', need:'Component integration requires attention to assembly clearances, repeated loading, temperature exposure and end-of-life separation.', products:['Mobility foam components','Vehicle protective inserts'], image:'technical'},
 {name:'Domestic appliances', intro:'Protect appliances in transit and integrate polymer parts into everyday equipment.', need:'Packaging must support the actual load path and handling route. Technical parts need a separate brief for fit, heat and operating conditions.', products:['Appliance protective packaging','Appliance technical parts'], image:'packaging'},
 {name:'Logistics & handling', intro:'Make the movement, storage and return of goods part of your packaging specification.', need:'Consider stacking loads, usable volume, cleaning, return journeys and how operators lift or access the packed product.', products:['Plastic pallets','Industrial storage bins','Custom cushioning foams','Polystyrene insulated boxes','Stackable delivery boxes','Catering transport boxes','Foldable insulated boxes','Reusable industrial containers','Reusable industrial coolers','Lightweight foam pallets'], image:'packaging'},
 {name:'Sports & leisure', intro:'Explore lightweight forms for equipment, accessories and protective applications.', need:'Define the sport, user group, anticipated impacts and test requirements. Material choice alone does not demonstrate protective performance.', products:['Sports accessories','Custom sports equipment','Leisure equipment components'], image:'technical'},
 {name:'Childhood', intro:'Develop play products and accessories with a clear focus on their intended age group.', need:'Child-accessible components require careful evaluation of edges, detachable parts, cleaning and the relevant safety standards.', products:['Moulded plastic toys','Childhood accessories'], image:'technical'},
 {name:'Agrifood', intro:'Give fresh food, prepared meals and frozen products packaging suited to their journey.', need:'Food-contact suitability, filling conditions, sealing equipment and the time-temperature profile all affect the packaging specification.', products:['Meat packaging','Fresh fish packaging','Catering packaging','Cheese packaging','Bakery packaging','Ice cream packaging','Fruit & vegetable packaging','Custom food packaging','Seafood presentation platters','Shellfish trays','Reusable food containers','Skin packaging boards','Gastronorm catering trays','Last-mile fresh produce trays','Retail food trays','Minced meat trays','High-volume food trays','Peel-seal trays','Skin-seal food trays','Clear multipurpose containers','Attached-lid takeaway trays','Insulated food trays'], image:'food'},
 {name:'Building', intro:'Consider insulation and lightweight forms as part of a complete building system.', need:'Thermal design, compressive loads, moisture exposure and installation details must be assessed against the project and local requirements.', products:['Structural foam forms','Custom building insulation','Under-screed insulation pads'], image:'technical'},
 {name:'Pharma & health', intro:'Plan temperature-sensitive shipments around the product, route and qualification protocol.', need:'A shipping container is one part of a qualified system. Payload, coolant, handling time and route conditions need to be evaluated together.', products:['Insulated pharmaceutical cases','Custom pharmaceutical packaging','Modular dry-ice containers','Dry-ice transport crates'], image:'packaging'},
 {name:'Insulation & waterproofing', intro:'Connect thermal insulation, roof design and water management at system level.', need:'Drainage, waterproofing interfaces, substrate loads and the specified roof build-up need coordinated detailing.', products:['Roof terrace insulation','Urban revegetation components','Drainage landscaping forms'], image:'technical'},
 {name:'Swimming pools & filtration', intro:'Explore insulation blocks and shaped components for pool construction.', need:'Select components alongside structural design, lining details, hydraulic equipment and the installation method.', products:['Custom swimming pool insulation','Swimming pool EPS blocks','Expanded polystyrene pool forms','Pool staircase & deck kits','Pool thermal panels'], image:'technical'}
].map((m,i)=>({...m,slug:slugify(m.name),number:String(i+1).padStart(2,'0')}));
const additionalFamilies:Record<string,string[]>={
 'Sports & leisure':['Foam exercise jump boxes'],
 'Agrifood':['Perishable goods transport boxes','Foam seafood platters','Compartment meal trays','Ice cream presentation trays','Insulated dessert boxes','Rigid food trays'],
 'Pharma & health':['Temperature-sensitive shipping boxes'],
 'Insulation & waterproofing':['Moulded drainage panels'],
 'Logistics & handling':['EPS transport boxes'],
};
legacyMarkets.forEach(m=>{m.products.push(...(additionalFamilies[m.name]||[]),...expandedFamilies.filter(f=>f.marketSlug===m.slug).map(f=>f.name));});
const eppIndustries = new Set(['hvac','mobility','logistics-handling','sports-leisure','childhood']);
const unsupportedProducts = new Set(['plastic-pallets','industrial-storage-bins','polystyrene-insulated-boxes','eps-transport-boxes','condensate-collection-trays','fan-coil-structural-supports','vehicle-parts-shuttle-trays','moulded-plastic-toys']);
export const products = legacyMarkets.flatMap(m=>m.products.map((name,i)=>({name,slug:slugify(name),market:m.name,marketSlug:m.slug,image:m.image,material:'EPP',summary: `${name} for ${m.name.toLowerCase()} applications. Explore the format, material and validation questions that guide a suitable specification.`, application:m.need,index:i}))).concat([{name:'Adhesive foam support pads',slug:'adhesive-foam-support-pads',market:'Logistics & handling',marketSlug:'logistics-handling',image:'packaging',material:'Cellular foam',summary:'Shaped support pads for positioning products within a protective packaging assembly.',application:'Specify the contact area, adhesive compatibility, surface finish and anticipated vibration before choosing the pad geometry.',index:10},{name:'Extendable protective corners',slug:'extendable-protective-corners',market:'Furniture',marketSlug:'furniture',image:'packaging',material:'Cellular foam',summary:'Adaptable corner protection for finished surfaces and variable product dimensions.',application:'Check edge geometry, adjustment range and abrasion risk through the actual transport cycle.',index:4}]).filter(product=>eppIndustries.has(product.marketSlug)&&!unsupportedProducts.has(product.slug));
products.forEach(p=>{if(productCopy[p.name])p.summary=productCopy[p.name].summary;const extra=expandedFamilies.find(f=>f.name===p.name);if(extra){p.material=extra.material;p.application=extra.application;}p.material='EPP';const sales=productSalesCopy[p.slug as keyof typeof productSalesCopy];if(sales)p.summary=sales.summary;});
/** The four industries offered in public navigation, forms and catalogue browsing. */
export const markets = [
 {slug:'sports-leisure',name:'Sports, Leisure & Early Childhood',sourceSlugs:['sports-leisure','childhood'],intro:'Shape lightweight equipment, play forms and accessories around the people who use them.',need:'Define the activity, age group, anticipated loads and cleaning conditions. Evaluate the complete design against its intended use and relevant safety requirements.',image:'technical'},
 {slug:'logistics-handling',name:'Logistics & Material Handling',sourceSlugs:['logistics-handling'],intro:'Protect, organise and move products through storage, transport and return journeys.',need:'Consider stacking loads, usable volume, cleaning, return journeys and how operators lift or access the packed product.',image:'packaging'},
 {slug:'hvac',name:'HVAC',sourceSlugs:['hvac'],intro:'Bring insulation, air management and assembly into a more considered component design.',need:'Airflow geometry, thermal interfaces, acoustic behaviour and access for servicing belong in the same design brief.',image:'technical'},
 {slug:'mobility',name:'Automotive',sourceSlugs:['mobility'],intro:'Develop lightweight vehicle components and protective inserts around the complete automotive assembly.',need:'Review assembly clearances, repeated loading, temperature exposure, handling and end-of-life separation.',image:'technical'},
].map((market,index)=>({...market,intro:industryStories[market.slug].intro,number:String(index+1).padStart(2,'0'),products:products.filter(product=>market.sourceSlugs.includes(product.marketSlug)).map(product=>product.name)}));
/** Resolve an original product application to its current public industry. */
export const publicMarketFor = (sourceSlug:string) => markets.find(market=>market.sourceSlugs.includes(sourceSlug));
/** Expand a public industry filter without changing original product/format keys. */
export const marketSourceSlugs = (slug:string) => markets.find(market=>market.slug===slug)?.sourceSlugs || [slug];
export const activeProducts = products.filter(product=>publicMarketFor(product.marketSlug));
products.forEach(product=>{const market=publicMarketFor(product.marketSlug);if(market)product.market=market.name;});
/** Public records take precedence while every original market URL remains available. */
export const allMarkets = markets;
export const materials = [
 {name:'Expanded polypropylene',short:'EPP',text:'Expanded polypropylene (EPP) is a lightweight, closed-cell bead foam moulded into protective packaging, insulation and technical components. Its performance depends on grade, density and part design.',consider:'Review impact response, dimensional tolerances, temperature exposure and the planned reuse cycle.'},
 {name:'EPP grade selection',short:'EPP GRADES',text:'Compare expanded polypropylene grades around density, processing, component geometry and operating conditions.',consider:'Select the grade around your component requirements. Discuss moulded density, repeated loads, temperature exposure and representative samples with PARK before agreeing the specification.'},
 {name:'Circular material options',short:'CIRCULAR',text:'Recycled-content EPP options should be assessed against application requirements and available material documentation.',consider:'Ask for traceability, declared recycled content, the measurement basis and an achievable end-of-life route.'}
].map(m=>({...m,slug:slugify(m.name)}));
export const expertise = [
 {name:'Foam moulding',text:'Shape bead foams into protective packaging, insulation assemblies and lightweight technical components.',details:'Define density, wall thickness, geometry, inserts and assembly interfaces early. Prototype evaluation should include real loading and environmental conditions.'},
 {name:'Cellular foam cutting',text:'Create precisely fitted inserts and cushions around the product that needs protection.',details:'The product dimensions, handling route and allowable movement guide the cavity layout. Evaluate compression and surface contact using representative samples.'},
 {name:'Co-development',text:'Translate an application brief into material, geometry and validation decisions.',details:'Gather drawings, operating conditions, volumes and constraints. Compare design options with a documented set of criteria before selecting a concept.'},
 {name:'Research & development',text:'Investigate material and design options against a defined technical question.',details:'Use a clear hypothesis, representative samples and measurable acceptance criteria. Research results should be tied to the actual application conditions.'},
 {name:'Numerical simulation',text:'Explore design behaviour before committing to physical tooling.',details:'Simulation needs realistic material data and boundary conditions. It supports design decisions but still requires correlation with physical tests.'},
 {name:'Testing & validation',text:'Build an evidence-based qualification plan around the finished application.',details:'Specify the test method, sample preparation, environment and pass criteria. Keep component-level findings distinct from complete-system certification.'},
 {name:'Industrialisation',text:'Prepare the design, tooling and process controls for a repeatable production route.',details:'Review tolerances, inspection, assembly, packaging and change control. Production approval should follow the agreed validation and sampling plan.'}
].map(e=>({...e,slug:slugify(e.name)}));
export const solutions = [
 {name:'Reduce weight',text:'Compare the total assembly, not just a material density. Geometry, integration and transport requirements determine whether a lighter design is useful.'},
 {name:'Reduce environmental impact',text:'Document material use, reuse assumptions and transport distances. Environmental comparisons need a defined boundary and credible data.'},
 {name:'Develop new ideas',text:'Start with the problem your current component cannot solve. A measurable brief makes it easier to compare material and manufacturing options.'},
 {name:'Preserve contents',text:'Assess the product sensitivity, shipment duration and handling route. Packaging must be validated as part of the complete distribution system.'},
 {name:'Manage temperature',text:'Plan insulation thickness, interfaces and coolant around the actual time-temperature profile. Confirm the design through representative testing.'},
 {name:'Protect in transit',text:'Identify impact, vibration, stacking and abrasion hazards. Build protection around the product’s vulnerable surfaces and load paths.'},
 {name:'Improve presentation',text:'Match form, surface finish and pack opening to the product experience while keeping filling and recovery requirements in view.'}
].map(s=>({...s,slug:slugify(s.name)}));
export const articles = [
 {slug:'epp-grade-selection',title:'Choose the right EPP grade for your application',category:'Material selection',intro:'EPP grades and moulded densities support different design requirements. Begin with the component’s job and the conditions it will see.',sections:[['Describe the job first','Record how the part will be loaded, how often it will be handled and what temperatures it will encounter. Protection, insulation and structural support call for different evaluation plans.'],['Compare finished designs','Density alone does not predict the result. Wall thickness, ribs, interfaces and available space can matter just as much. Compare representative components with a common test plan.'],['Plan recovery from the start','A theoretical recycling route is not the same as an accessible one. Check collection, material separation and handling arrangements in the intended region.']]},
 {slug:'cold-chain-packaging-brief',title:'A better brief for cold-chain packaging',category:'Packaging guide',intro:'Temperature-sensitive shipping begins with a clear route profile. The container, payload and coolant need to work as one system.',sections:[['Map the shipment','Specify the payload, acceptable temperature range, duration, transfer points and likely seasonal extremes. Include delays rather than only the ideal journey.'],['Define the complete pack','Document product placement, coolant preparation, insulation format and packing instructions. Changing one part of the system can change its temperature behaviour.'],['Qualify representative conditions','Select the test protocol and acceptance criteria with the product owner. Record the pack configuration and measurements so the result can be reproduced.']]},
 {slug:'design-for-reuse',title:'Designing returnable packaging for real journeys',category:'Circular design',intro:'Returnable packaging works when the return journey, cleaning process and handling behaviour have been planned as carefully as the outbound shipment.',sections:[['Build the return loop','Identify who collects the packaging, where it is stored and how empties travel. Folding or nesting can help, but only when operators can use the feature reliably.'],['Understand repeated use','Consider abrasion, impact, cleaning chemicals and missing components. Choose inspection criteria that tell operators when to repair or retire a container.'],['Measure the operating system','Track loss rate, actual reuse cycles and transport requirements. Use these observations before making environmental or cost claims.']]},
 {slug:'technical-part-design',title:'From a technical drawing to a useful prototype',category:'Engineering',intro:'A successful prototype answers a specific question. It should reveal whether a design works in the assembly, rather than simply reproduce its shape.',sections:[['Capture the interfaces','List contact surfaces, fasteners, seals, tolerances and service access. These details often control the usefulness of a component more than its exterior appearance.'],['Select a realistic prototype','Match the prototype method to the behaviour under investigation. A visual model may not represent the mechanical or thermal response of a production part.'],['Agree the next decision','Define the measurements that will support a design change, tooling commitment or additional test. Keep the result tied to that decision.']]}
];
