import expandedFamilies from './expanded-families.json';
import {industryStories} from './industry-stories';
type Copy={summary:string;focus:string[]};
const rows=`Custom HVAC components|Shaped components that bring air-channel geometry, insulation and equipment interfaces into one coordinated design.|Air channel dimensions;Condensation interfaces;Assembly tolerances
Moulded air ducts|Lightweight shaped air passages for connecting sections of an HVAC assembly with a defined airflow path.|Pressure and flow;Duct connections;Access for cleaning
HVAC insulation housings|Fitted insulation shells around equipment sections, pipework interfaces and thermally sensitive assemblies.|Thermal bridges;Wall thickness;Seal locations
Aircraft interior components|Polymer and foam components for cabin interior development, selected around the installation and approval requirements.|Fire qualification;Interior interfaces;Traceability
Lightweight aviation inserts|Shaped lightweight inserts for supporting, separating or integrating elements within an aircraft interior assembly.|Part weight;Attachment method;Approval evidence
Protective furniture foams|Fitted foam supports that separate vulnerable furniture surfaces from packaging and handling loads.|Surface contact;Compression response;Upholstery protection
Corner protectors|Shaped corner cushions that cover vulnerable edges during packing, storage and shipment.|Edge geometry;Impact direction;Surface abrasion
EPP foam sheets|Flat foam stock for inserts, liners, cushioning studies and shaped components made through cutting or machining.|Thickness;Density;Cutting method
Foam furniture|Lightweight shaped foam forms for seating cores, furniture concepts and supported upholstered designs.|Seat geometry;Repeated loading;Upholstery attachment
Mobility foam components|Lightweight moulded forms for vehicle assemblies where integration, packaging space and component handling matter.|Assembly interfaces;Temperature exposure;Repeated loading
Vehicle protective inserts|Shaped inserts that hold or separate vehicle components through production handling and transport.|Cavity fit;Part retention;Return logistics
Appliance protective packaging|Fitted cushions, base supports and corner pieces for moving domestic appliances through a defined distribution route.|Appliance mass;Stacking loads;Transit impacts
Appliance technical parts|Moulded polymer components developed around the fit, attachment and operating conditions of an appliance.|Operating temperature;Attachment features;Part tolerances
Plastic pallets|Polymer pallet formats for moving unit loads, selected around handling equipment and the actual goods distribution system.|Fork entry;Static and dynamic loads;Cleaning conditions
Industrial storage bins|Containers for organising components, work-in-progress and returnable material flows.|Usable volume;Stacking arrangement;Lid and access
Custom cushioning foams|Product-specific foam inserts and support forms that control movement within the transport pack.|Fragile surfaces;Vibration route;Support geometry
Polystyrene insulated boxes|Cellular foam containers for temperature-sensitive shipments, specified as part of a complete pack configuration.|Payload volume;Coolant placement;Route duration
Stackable delivery boxes|Insulated delivery formats designed around filling, stacking and the last metres of the delivery journey.|Stacking interface;Handling grip;Payload fit
Catering transport boxes|Insulated containers for moving prepared meals and catering loads through a defined service route.|Meal format;Packing sequence;Cleaning method
Foldable insulated boxes|Collapsible insulated formats for applications where storage and return volume are important considerations.|Folded volume;Hinge durability;Insulation interfaces
Reusable industrial containers|Returnable containers for protected component handling, collection and storage across repeated journeys.|Cleaning cycles;Closure system;Service-life inspection
Reusable industrial coolers|Returnable insulated transport formats for repeated temperature-sensitive distribution cycles.|Thermal route;Lid retention;Return handling
Lightweight foam pallets|Foam pallet forms for lightweight unit-load handling and packaging development.|Load spread;Fork compatibility;Support position
Sports accessories|Moulded polymer and foam accessories for sport-specific equipment concepts and component development.|Intended activity;Grip and fit;Load conditions
Custom sports equipment|Custom-shaped sport and leisure components developed around user interaction and the intended equipment function.|User group;Mechanical loading;Test method
Leisure equipment components|Lightweight moulded parts for outdoor, recreation and leisure assemblies.|Outdoor exposure;Assembly method;Handling conditions
Moulded plastic toys|Moulded toy components developed with an intended age group, use pattern and safety evaluation in mind.|Age range;Detachable parts;Cleaning conditions
Childhood accessories|Foam and polymer accessories for children's product concepts, specified around their actual use and contact surfaces.|Accessible edges;Contact materials;Assembly retention
Meat packaging|Tray and container formats for meat presentation, filling and sealing workflows.|Sealing process;Product contact;Chilled route
Fresh fish packaging|Protective and insulated packaging formats for fresh fish handling, presentation and distribution.|Drainage;Cold-chain profile;Load and stacking
Catering packaging|Portion trays and takeaway formats for prepared food and professional catering workflows.|Portion volume;Lidding format;Filling conditions
Cheese packaging|Packaging formats that balance cheese presentation, product support and the selected closing process.|Product shape;Moisture conditions;Sealing interface
Bakery packaging|Presentation and transport formats for bakery products that need controlled positioning and surface protection.|Product height;Crush protection;Presentation
Ice cream packaging|Container and tray formats for frozen desserts, developed around filling, storage and serving conditions.|Freezing conditions;Lid fit;Serving format
Fruit & vegetable packaging|Handling and presentation formats for produce with different shape, loading and ventilation requirements.|Ventilation;Stacking;Bruise-sensitive surfaces
Custom food packaging|Application-specific food pack formats that coordinate the product, filling line, seal and distribution route.|Food-contact grade;Equipment fit;Recovery route
Seafood presentation platters|Rigid platter formats for presenting seafood while considering handling, moisture and product arrangement.|Platter geometry;Moisture resistance;Presentation
Shellfish trays|Rigid pack formats for shellfish and crustaceans where shape, product edges and closing requirements need particular attention.|Puncture resistance;Product arrangement;Seal geometry
Reusable food containers|Returnable food container concepts developed around collection, washing and repeated service.|Cleaning validation;Closure durability;Return loop
Skin packaging boards|Flat presentation and support formats for product packs using a selected skin-packaging process.|Film compatibility;Board geometry;Sealing equipment
Gastronorm catering trays|Catering tray formats specified around kitchen handling and the relevant gastronorm equipment interface.|Equipment format;Handling temperature;Tray rigidity
Last-mile fresh produce trays|Produce delivery formats for protecting an assembled order through the final delivery stage.|Order weight;Payload arrangement;Delivery duration
Retail food trays|Retail presentation trays selected around the food, shelf arrangement and sealing workflow.|Shelf format;Film selection;Product visibility
Minced meat trays|Tray formats for minced meat filling, presentation and the chosen sealing process.|Fill volume;Seal area;Chilled storage
High-volume food trays|Tray formats for production lines where handling consistency, nesting and lidding integration matter.|Line speed;Nesting behaviour;Sealing tool
Peel-seal trays|Tray formats with an opening experience that depends on the selected lidding film and sealing process.|Seal strength;Peel behaviour;Flange geometry
Skin-seal food trays|Food tray formats intended for evaluation within a skin-sealing packaging system.|Vacuum process;Film contact;Tool compatibility
Clear multipurpose containers|Transparent container formats for storage, presentation and a range of packaging applications.|Usable volume;Clarity;Closure fit
Attached-lid takeaway trays|Takeaway tray formats with an integrated lid for convenient filling and pack closing.|Hinge behaviour;Closure retention;Portion arrangement
Insulated food trays|Cellular food tray formats for applications that need thermal separation and product support.|Thermal duration;Product contact;Tray handling
Structural foam forms|Lightweight shaped forms used within a coordinated structural or construction method.|Structural design;Concrete interfaces;Installation method
Custom building insulation|Insulation shapes and boards selected around thermal design, available space and installation interfaces.|Thermal design;Moisture exposure;Compressive loading
Under-screed insulation pads|Insulation formats beneath floor build-ups, evaluated alongside loads, the substrate and the overall floor design.|Floor loads;Screed build-up;Thermal bridges
Insulated pharmaceutical cases|Insulated transport cases for developing qualified temperature-sensitive shipment systems.|Payload temperature;Coolant conditioning;Qualification protocol
Custom pharmaceutical packaging|Application-specific protective and insulated packs for healthcare logistics development.|Product sensitivity;Route profile;Packaging validation
Modular dry-ice containers|Insulated container concepts for controlled dry-ice transport applications.|Ventilation;Coolant handling;Compatible payload
Dry-ice transport crates|Crate formats for dry-ice logistics development, requiring a documented handling and shipment plan.|Dry-ice handling;Ventilation;Carrier requirements
Roof terrace insulation|Roof insulation formats selected as part of the waterproofing, load and thermal design of a roof build-up.|Membrane interface;Thermal design;Roof loads
Urban revegetation components|Shaped components for planted urban roof or landscape systems where drainage and installation interfaces matter.|Substrate loading;Water movement;Root-zone design
Drainage landscaping forms|Lightweight shaped elements for coordinating drainage spaces within a landscape installation.|Drainage path;Substrate loads;Outlet position
Custom swimming pool insulation|Application-specific insulation shapes for integrating with a pool structure and lining system.|Lining interface;Pool geometry;Thermal design
Swimming pool EPS blocks|Hollow foam block formats for pool construction methods developed with structural and installation requirements.|Reinforcement design;Interlocking details;Lining method
Expanded polystyrene pool forms|Shaped EPS components for a pool construction system with defined structural and hydraulic interfaces.|Structure design;Service penetrations;Installation sequence
Pool staircase & deck kits|Shaped staircase and deck concepts for pool projects, selected around geometry, loads and the lining system.|Step geometry;Surface finish;Structural support
Pool thermal panels|Insulation panel formats for evaluating heat transfer through pool construction interfaces.|Panel thickness;Thermal bridges;Substrate contact
Foam exercise jump boxes|Lightweight foam exercise-box concepts developed around training use, stability and repeated loading.|Box stability;Grip surface;Load testing
Perishable goods transport boxes|Insulated transport pack formats for perishable goods moving through a defined route and handling process.|Route temperature;Payload arrangement;Transit time
Foam seafood platters|Cellular foam presentation formats for seafood, selected around chilled handling and the plated product.|Cold conditions;Platter rigidity;Food-contact grade
Compartment meal trays|Meal tray formats that organise separate food portions within a coordinated filling and sealing workflow.|Compartment layout;Lid interface;Filling process
Ice cream presentation trays|Tray formats for arranging and presenting frozen dessert products.|Freezer conditions;Product arrangement;Tray depth
Insulated dessert boxes|Insulated box formats for protecting shaped desserts through handling and temperature-sensitive transport.|Dessert dimensions;Thermal route;Impact protection
Rigid food trays|Rigid tray formats for food presentation, sealing and handling within an agreed packaging workflow.|Food-contact grade;Seal compatibility;Pack stiffness
Temperature-sensitive shipping boxes|Insulated box concepts for products that need a controlled shipment temperature and documented pack configuration.|Temperature range;Shipping duration;Qualification plan
Moulded drainage panels|Cellular panels with shaped drainage spaces for roof and landscape system development.|Water capacity;Compression design;Outlet connections
EPS transport boxes|Lightweight EPS container formats for developing protective or insulated transport packs.|Box dimensions;Load support;Recovery route
Adhesive foam support pads|Cellular support pads for locating and supporting products inside a protective packaging unit.|Adhesive compatibility;Support area;Surface finish
Extendable protective corners|Adjustable corner protection concepts for product edges and changing packaging dimensions.|Adjustment range;Corner fit;Surface abrasion`;
export const productCopy:Record<string,Copy>=Object.fromEntries(rows.split('\n').map(row=>{const [name,summary,focus]=row.split('|');return [name,{summary,focus:focus.split(';')}];}));
Object.assign(productCopy,Object.fromEntries(expandedFamilies.map(f=>[f.name,{summary:f.summary,focus:f.focus}])));
export type Product={name:string;slug:string;market:string;marketSlug:string;material:string;summary:string;application:string;image:string};
export function productVisual(p: Product) {
  if (/ice cream tubs|ice cream presentation/i.test(p.name)) return '/images/products/icecream-tubs.webp';
  if (/heat-pump|hydraulic|water-heater|condensate|fan-coil/i.test(p.name)) return '/images/products/hvac-parts.webp';
  if (p.marketSlug === 'aviation') return '/images/products/aviation-seat.webp';
  if (p.marketSlug === 'mobility') {
    return /protective inserts|storage organizers|shuttle trays/i.test(p.name)
      ? '/images/products/mobility-inserts.webp'
      : '/images/generated/mobility.webp';
  }
  if (/helmet/i.test(p.name)) return '/images/products/helmet-liner.webp';
  if (/insole/i.test(p.name)) return '/images/products/foam-insoles.webp';
  if (/surfboard/i.test(p.name)) return '/images/products/surfboard-core.webp';
  if (/child-seat/i.test(p.name)) return '/images/products/child-seat.webp';
  if (p.marketSlug === 'childhood') return '/images/products/playforms.webp';
  if (/exercise jump box/i.test(p.name)) return '/images/generated/sports.webp';
  if (/macaron|cake|bakery filling|bakery assembly/i.test(p.name)) return '/images/products/bakery-inserts.webp';
  if (/corner|appliance protective|support pad/i.test(p.name)) return '/images/products/corners.webp';
  if (/sheet|protective furniture|cushion/i.test(p.name)) return '/images/products/sheets.webp';
  if (/pallet/i.test(p.name)) return '/images/products/pallet.webp';
  if (/drainage|revegetation|roof/i.test(p.name)) return '/images/products/drainage.webp';
  if (/board|floor insulation|thermal-break/i.test(p.name) && p.marketSlug === 'building') return '/images/products/sheets.webp';
  if (/pool.*block|pool forms|structural foam/i.test(p.name)) return '/images/products/poolblock.webp';
  if (/toy|childhood|foam furniture/i.test(p.name)) return '/images/products/playforms.webp';
  if (p.marketSlug === 'agrifood' && !/box/i.test(p.name)) return '/images/products/trays.webp';
  if (/box|cooler|case|container|crate/i.test(p.name) && p.marketSlug !== 'agrifood') return '/images/products/cooler.webp';
  if (p.marketSlug === 'agrifood') return '/images/food.webp';
  if (p.marketSlug === 'logistics-handling') return '/images/packaging.webp';
  if (p.marketSlug === 'sports-leisure') return '/images/generated/sports.webp';
  return '/images/technical.webp';
}
export const marketGuides:Record<string,{overview:string;applications:string[];priorities:[string,string][];faq:[string,string][]}>={
 'hvac':{overview:'HVAC components have to fit within a working system. Air movement, insulation, access and assembly often compete for the same space. A shaped foam housing or duct can be explored around these interfaces rather than treated as a separate piece of packaging.',applications:['Air handling assemblies','Ventilation channels','Insulated equipment housings','Thermal and acoustic interfaces'],priorities:[['Start with airflow','Record the air path, connections, required flow and allowable resistance. A duct geometry should be assessed within the equipment rather than in isolation.'],['Coordinate the interfaces','Keep seal locations, service access, fasteners and condensation-sensitive surfaces in the design review.'],['Prototype realistically','Use representative materials and operating conditions when investigating fit, thermal behaviour or noise.']],faq:[['Which material should I start with?','The answer depends on heat exposure, geometry, load and processing. EPP foam and rigid moulded polymers support different design routes. Compare the finished design with its requirements.'],['Can insulation and air management share one part?','A combined component is a design option. It needs a review of air paths, thermal interfaces, sealing and the manufacturing route.']]},
 'aviation':{overview:'Aircraft interior development begins with the installation and approval route. Lightweight foam or polymer components can be studied for fit and integration, while traceability, environmental exposure and the applicable test requirements remain part of the brief.',applications:['Cabin interior integration','Lightweight support inserts','Interior component packaging','Assembly and service interfaces'],priorities:[['Define the approval route','Identify the aircraft application, relevant requirements and documentation expected from the material and component suppliers.'],['Review complete assemblies','A sample material result does not establish the performance of a finished component. Include attachments, coverings and neighbouring parts.'],['Keep traceability visible','Agree material identification, revision control and the evidence required at each project milestone.']],faq:[['Are these components automatically aircraft approved?','No blanket qualification is implied by a product family. Approval depends on the specific grade, component design, installation and applicable test evidence.'],['What should the first brief contain?','Include the installation area, drawing, interfaces, weight target and the approval process that the finished component must follow.']]},
 'furniture':{overview:'Foam can play two different roles in a furniture project: it can become part of the furniture itself, or it can protect the finished item on its journey. Distinguishing those roles helps select the right shape, surface interface and evaluation plan.',applications:['Seating cores and shaped furniture','Protective corners and edge cushions','Flat foam inserts and liners','Delivery packaging'],priorities:[['Protect the finish','Review painted, polished and upholstered surfaces for abrasion and pressure marks. Cushion contact areas should suit the finish.'],['Understand repeated loading','For furniture cores, define the loading pattern, user interaction and expected service conditions.'],['Plan packing and unpacking','Make the protective format practical for operators, assembly, return journeys and material separation.']],faq:[['How do I specify a corner protector?','Share edge dimensions, surface finish, product weight and the anticipated impact directions during transit.'],['Can the same foam serve a furniture core and transport pack?','The requirements are different. Compare the relevant load, comfort and protection behaviours before selecting a common grade.']]},
 'mobility':{overview:'Lightweight vehicle components need to earn their place within an assembly. A moulded foam part can be explored for integration, component separation or packaging, with temperature, fit and repeated handling evaluated around the actual vehicle environment.',applications:['Vehicle component integration','Protective production inserts','Lightweight moulded forms','Returnable component handling'],priorities:[['Map component interfaces','List contact surfaces, clips, fasteners, clearances and the parts that share the available space.'],['Consider real exposure','Temperature, vibration, fluids and assembly loads determine the evidence needed for a design decision.'],['Design the handling loop','For component packaging, include the loading station, return journey and inspection process.']],faq:[['Does low density alone make a lighter vehicle part?','The whole design matters. Thickness, reinforcement, attachments and integration affect the total part or assembly weight.'],['What makes a useful development sample?','A sample should represent the material and geometry needed to answer the current design question, with an agreed test and comparison method.']]},
 'domestic-appliances':{overview:'Domestic appliances need protection during distribution and functional parts during operation. A shipping cushion should follow the appliance load path; a technical component should be evaluated against its operating environment and assembly interfaces.',applications:['Appliance base supports','Transit corner cushions','Internal polymer components','Fitted assembly inserts'],priorities:[['Support the load','Identify the appliance centre of gravity, support points and the loads created by stacking and handling.'],['Separate shipping from service','Transport packs and installed technical parts need different requirements and validation methods.'],['Work around the assembly','Coordinate clips, screw bosses, seals, heat sources and the available maintenance space.']],faq:[['What information is needed for appliance packaging?','Include packed weight, support points, distribution route, stacking arrangement and the vulnerable surfaces.'],['Can fitted cushions be reused?','Reuse should be planned around actual return handling, damage checks and storage arrangements. The material label alone does not establish a reuse programme.']]},
 'logistics-handling':{overview:'Good logistics packaging fits the entire journey. Pallets, bins, insulating boxes and protective inserts should work with the handling equipment, loading process and return arrangements used by the operation.',applications:['Unit-load pallets','Industrial storage and returnable bins','Temperature-sensitive delivery','Custom product cushioning'],priorities:[['Follow the load through the route','Consider loading, stacking, vehicle movement, unloading and intermediate storage. Each stage can create a different hazard.'],['Make returnable formats practical','Define collection, empty storage, cleaning, inspection and loss management before choosing a returnable pack.'],['Evaluate the complete unit','A pallet, container, insert and payload behave as one handling unit. Test the assembled configuration.']],faq:[['How should a pallet be specified?','State dimensions, load distribution, static and handling conditions, fork access and the equipment used along the route.'],['What matters for returnable bins?','Usable volume, stacking, closure, cleaning, return storage and a practical damage inspection process all belong in the brief.']]},
 'sports-leisure':{overview:'Sports, leisure and early-childhood products connect lightweight forms with movement, play and repeated handling. Equipment, accessories and moulded play components need a brief built around the activity, intended age group and complete product design.',applications:['Exercise and training components','Moulded sports accessories','Leisure equipment parts','Lightweight play forms','Moulded toy components','Early-childhood accessories'],priorities:[['Define the activity and age group','Record user age, movement, loads, accessible edges and foreseeable handling before developing the component.'],['Review contact, grip and cleaning','Consider stability, surface contact, detachable parts, finishes and the cleaning method within the complete assembly.'],['Validate the finished product','Agree realistic loading, repeated-use and relevant product-safety tests. Material choice alone does not establish protective performance or child safety.']],faq:[['Can sports and play products use the same foam grade?','Select the grade around the component, age group, loading and contact conditions. Similar-looking products can need different materials and validation.'],['What should be included in a development brief?','Share the intended activity and age range, drawings, attachment details, cleaning conditions and the requirements the finished product must meet.']]},
 'childhood':{overview:'Children’s products need a careful connection between age group, materials and the way the product can be handled. Rounded forms are a design feature, while product safety still depends on the complete assembly and the applicable evaluation.',applications:['Moulded toy components','Lightweight play forms','Children’s accessories','Product supports and inserts'],priorities:[['Start with the age group','Accessible edges, detachable parts, entrapment spaces and foreseeable handling depend on the intended user.'],['Specify contact and cleaning','Evaluate materials and finishes against their contact conditions and the cleaning method.'],['Test the complete product','Include attachments, covers, joints and any small components in the evaluation plan.']],faq:[['Does a soft foam make a toy safe?','Softness is only one characteristic. The full design, parts, use conditions and applicable safety evaluation matter.'],['What details should a supplier receive?','Share the age range, drawing, contact surfaces, assembly method and cleaning conditions with the relevant requirements.']]},
 'agrifood':{overview:'Food packaging should work from filling through transport, presentation and opening. Trays, boxes and containers need to be selected around the food, the closing system, the time-temperature route and the handling conditions.',applications:['Meat and seafood','Fresh fruit and vegetables','Prepared meals and catering','Bakery and frozen desserts','Retail trays and skin packs','Returnable food containers'],priorities:[['Bring the filling line into the brief','Tray shape, flange, nesting and rigidity need to suit the filling and closing equipment.'],['Match the route to the food','Record the product sensitivity, planned temperatures, duration and the handling steps.'],['Confirm the specific grade','Food-contact documentation, sealing compatibility and temperature suitability must match the selected material and application.']],faq:[['Can one tray work with every lidding film?','Compatibility depends on the tray material, flange geometry, film and sealing process. Evaluate the intended combination.'],['Which details matter for an insulated food box?','Payload size, packing sequence, coolant, shipping duration and the required temperature range define the complete pack.']]},
 'building':{overview:'Insulation and shaped foam forms belong within a coordinated building design. Thermal requirements, loads, moisture exposure and installation details should be reviewed together rather than selected from a material description alone.',applications:['Thermal insulation boards','Custom insulation shapes','Under-screed layers','Lightweight structural forms'],priorities:[['Review the build-up','Document adjoining layers, substrates, support conditions and penetrations.'],['Coordinate thermal and load requirements','Available thickness, compression and thermal bridges can influence each other in a complete design.'],['Specify installation details','Site handling, fitting, protection before covering and inspection affect the completed installation.']],faq:[['Can an insulation material be chosen only by thickness?','Grade, thermal properties, loading, moisture and the surrounding construction all affect suitability.'],['What should be agreed before ordering?','Confirm the drawing, dimensions, grade, installation method and evidence required for the building system.']]},
 'pharma-health':{overview:'A temperature-sensitive shipping pack is a system: insulation, coolant, product arrangement and route all influence the result. Healthcare packaging development should begin with the product requirements and the qualification protocol.',applications:['Insulated pharmaceutical cases','Custom healthcare packs','Temperature-sensitive shipping','Dry-ice container development'],priorities:[['Describe the route','Include duration, handovers, delays and seasonal conditions instead of only an ideal shipment.'],['Define the full pack','Document payload, coolant preparation, packing instructions, monitoring and closure.'],['Agree qualification','Select a suitable test method and acceptance criteria with the product owner. Keep the qualified configuration under change control.']],faq:[['Is an insulated box enough to qualify a cold chain?','The full pack and route need to be qualified against the product’s requirements. A box by itself does not establish a temperature claim.'],['What needs special attention with dry ice?','Handling, ventilation, payload compatibility and carrier requirements should be addressed in the shipment plan.']]},
 'insulation-waterproofing':{overview:'Roof terraces and planted surfaces need insulation, waterproofing and water management to work together. Shaped drainage and insulation elements should be coordinated with the membrane, substrate, outlets and load design.',applications:['Roof terrace insulation','Planted roof systems','Drainage panels','Landscape water management'],priorities:[['Coordinate water movement','Review drainage paths, outlets and temporary retention within the complete roof or landscape system.'],['Understand loading','Include substrate, water, access and permanent loads when evaluating compression and support.'],['Protect interfaces','Waterproofing, root-zone layers and insulation must be detailed around the specified build-up.']],faq:[['Can a drainage panel replace a complete roof design?','No. It is one element within a system that includes waterproofing, outlets, layers and loading requirements.'],['What should the drawing show?','Include the substrate, membrane, slopes, outlets, penetrations and adjoining layers.']]},
 'swimming-pools-filtration':{overview:'Foam pool forms and insulation components are selected alongside structural design, the lining system and hydraulic equipment. A fitted form needs to work with reinforcement, penetrations, finishes and the installation sequence.',applications:['EPS pool construction blocks','Custom pool insulation','Staircase and deck forms','Thermal panels'],priorities:[['Begin with the pool structure','Record geometry, reinforcement, support and the specified construction method.'],['Detail the lining interface','Edges, steps, joints and service penetrations should be coordinated with the lining or finish.'],['Plan installation','Consider handling, cutting, temporary stability and the order in which components are fitted.']],faq:[['Are these filtration devices?','This catalogue section covers pool insulation and shaped construction components. Hydraulic filtration equipment should be specified separately.'],['What information is needed for custom forms?','Share pool geometry, structural method, lining system, step dimensions and service penetrations.']]}
};

// Keep product-page context in step with the current four industry stories.
for (const [slug, story] of Object.entries(industryStories)) {
  marketGuides[slug] = {
    overview: story.overview.body,
    applications: story.applications.map(application => application.title),
    priorities: story.benefits.map(benefit => [benefit.title, benefit.text]),
    faq: story.faq.map(item => [item.question, item.answer]),
  };
}
marketGuides.childhood = marketGuides['sports-leisure'];
