import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {markets,allMarkets,activeProducts,materials,products,expertise,solutions,articles,origin} from '../../../lib/catalog';
import {Breadcrumb,CTA,PageHero} from '../../../components/shared';
import {Icon,ProductCard,Film} from '../../../components/ui';
import {marketGuides} from '../../../lib/content';
import {marketImagePath} from '../../../lib/navigation';
import {resourcePages,aboutPages,customExpertise} from '../../../lib/resource-pages';
import {marketPages,additionalMarketGuides,marketProductSlugs,isDrainageProduct} from '../../../lib/market-pages';
import technicalData from '../../../lib/technical-guides.json';
import FormatExplorer from '../../../components/FormatExplorer';
import {DetailedGuide} from '../../../components/ReferenceDetails';
import EppMaterialGuide from '../../../components/EppMaterialGuide';
import EppVsEpsGuide from '../../../components/EppVsEpsGuide';
import ReuseGuide from '../../../components/ReuseGuide';
import IndustryDetail from '../../../components/IndustryDetail';
import EppProductDetail from '../../../components/EppProductDetail';
import {industryStories} from '../../../lib/industry-stories';
const tables={markets:[...allMarkets,...marketPages],materials,products,expertise:[...expertise,customExpertise],solutions,resources:[...articles,...resourcePages],about:aboutPages};
type Section=keyof typeof tables;
export function generateStaticParams(){return Object.entries(tables).flatMap(([section,rows])=>rows.map(row=>({section,slug:row.slug})));}
export const dynamicParams=false;
export async function generateMetadata({params}:{params:Promise<{section:string,slug:string}>}):Promise<Metadata>{const {section,slug}=await params;const row=tables[section as Section]?.find(x=>x.slug===slug);if(!row)return {};const title='title' in row?row.title:row.name;const desc=section==='markets'&&industryStories[slug]?industryStories[slug].intro:'summary' in row?row.summary:'intro' in row?row.intro:row.text;const archived=(section==='markets'&&!markets.some(m=>m.slug===slug))||(section==='products'&&!activeProducts.some(p=>p.slug===slug));return {title,description:desc,...(archived?{robots:{index:false,follow:true}}:{}),alternates:{canonical:`/${section}/${slug}/`},openGraph:{title,description:desc,...(section==='markets'&&industryStories[slug]?{images:[{url:industryStories[slug].heroImage,width:1440,height:960,alt:industryStories[slug].heroAlt}]}:{}),url:`/${section}/${slug}/`,type:section==='resources'?'article':'website'}};}
export default async function Detail({params}:{params:Promise<{section:string,slug:string}>}){const {section,slug}=await params;const row=tables[section as Section]?.find(x=>x.slug===slug);if(!row)notFound();const name='title' in row?row.title:row.name;const schema={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:origin},{'@type':'ListItem',position:2,name:section,item:`${origin}/${section}/`},{'@type':'ListItem',position:3,name,item:`${origin}/${section}/${slug}/`}]};const crumbs=[{name:section.charAt(0).toUpperCase()+section.slice(1),href:`/${section}/`},{name}];
 if(section==='products'){const product=products.find(item=>item.slug===slug)!;return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><div className="container"><Breadcrumb items={crumbs}/></div><EppProductDetail product={product}/></>;}
 if(section==='markets'&&industryStories[slug]){return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><div className="container"><Breadcrumb items={crumbs}/></div><IndustryDetail story={industryStories[slug]}/></>;}
 if(section==='markets'){const m=[...allMarkets,...marketPages].find(x=>x.slug===slug)!;const guide=additionalMarketGuides[m.slug as keyof typeof additionalMarketGuides]||marketGuides[m.slug];return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><div className="container"><Breadcrumb items={crumbs}/></div><PageHero eyebrow={`MARKET ${m.number} / ${m.name.toUpperCase()}`} title={`Possibilities for ${m.name.toLowerCase()}.`} text={m.intro} image={marketImagePath(m.slug)}/><section className="section detail-body"><div><p className="eyebrow">BUILT AROUND THE APPLICATION</p><h2>Understand the need.<br/>Then shape the answer.</h2><p>{guide.overview}</p><h3>Application areas</h3><ul>{guide.applications.map(a=><li key={a}>{a}</li>)}</ul><p>{m.need}</p><p>Bring dimensions, operating conditions, assembly constraints and the expected service life into your brief. Compare candidate designs using representative samples and agreed acceptance criteria.</p></div><aside className="aside-box"><h3>Ask the right questions.</h3><p>What must the component protect, support or insulate? How will it be installed, transported and recovered?</p><Link href="/contact/">Create your project brief →</Link></aside></section><section className="section tight-top"><div className="focus-grid">{guide.priorities.map(([h,t])=><div key={h}><h3>{h}</h3><p>{t}</p></div>)}</div></section><section className="section tight-top"><div className="section-heading"><h2>Explore product families.</h2><span>{m.products.length} application starting points</span></div><div className="product-grid">{products.filter(p=>marketProductSlugs(m.slug).includes(p.marketSlug)&&(m.slug!=='revegetation-drainage'||isDrainageProduct(p.name))).map(p=><ProductCard key={p.slug} product={p}/>)}</div></section><CTA/></>;}
 if(section==='resources'&&slug==='epp-or-eps'){return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><div className="container"><Breadcrumb items={crumbs}/></div><EppVsEpsGuide/></>;}
 if(section==='resources'&&slug==='design-for-reuse'){return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><div className="container"><Breadcrumb items={crumbs}/></div><ReuseGuide/></>;}
 if(section==='resources'||section==='about'){const a=[...articles,...resourcePages,...aboutPages].find(x=>x.slug===slug)!;return <><div className="container"><Breadcrumb items={crumbs}/></div><PageHero eyebrow={`${a.category.toUpperCase()} / 3 MIN READ`} title={a.title} text={a.intro}/>{slug==='standard-catalogue'&&<FormatExplorer/>}<article className="editorial article-body">{a.sections.map(([h,t])=><section key={h}><h2>{h}</h2><p>{t}</p></section>)}{"download" in a&&<a className="button" href={String(a.download)} download>Download PDF guide <Icon kind="download"/></a>}{"video" in a&&<div className="park-download"><Film/></div>}<aside className="article-note">This guide provides general design considerations. Confirm application suitability and test requirements with your supplier or technical adviser.</aside><Link className="button" href="/contact/">Turn this into a brief <Icon kind="arrow"/></Link></article><CTA/></>;}
 if(section==='materials'&&slug==='expanded-polypropylene'){const material=materials.find(item=>item.slug===slug)!;return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><div className="container"><Breadcrumb items={crumbs}/></div><PageHero eyebrow="MATERIALS / EPP" title="Expanded polypropylene (EPP)" text={material.text} image="technical"/><EppMaterialGuide/><CTA/></>;}
 const v=(section==='materials'?materials:section==='expertise'?[...expertise,customExpertise]:solutions).find(x=>x.slug===slug)!;return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><div className="container"><Breadcrumb items={crumbs}/></div><PageHero eyebrow={section.toUpperCase()} title={v.name} text={v.text} image={section==='materials'?'technical':undefined}/><section className="section detail-body"><div><p className="eyebrow">A PRACTICAL STARTING POINT</p><h2>{section==='materials'?'Choose around the application.':section==='expertise'?'Connect the process to the purpose.':'Define what a better result means.'}</h2><p>{'consider' in v?String(v.consider):'details' in v?String(v.details):'Start by documenting the existing design, the specific problem and how an improvement will be measured. Include operating conditions, assembly constraints and the intended service life.'}</p><h3>Questions to bring to the conversation</h3><ul><li>What is the application, and which requirements are essential?</li><li>How will the finished component be manufactured and assembled?</li><li>Which conditions should be represented in testing?</li><li>What happens at the end of the useful service life?</li></ul><p>Any performance, food-contact or environmental claim needs evidence for the specific grade and application. Agree the validation and documentation requirements before selecting a final design.</p></div><aside className="aside-box"><Icon kind="layers"/><h3>See the possibilities.</h3><p>Explore product families and industries to build a more specific brief.</p><Link href="/products/">Browse products →</Link><Link href="/markets/">Explore industries →</Link></aside></section><DetailedGuide guide={technicalData.find(g=>g.slug===slug&&g.section===section)}/><CTA/></>;}
