import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {markets,materials,products,expertise,solutions,articles,origin} from '../../../lib/catalog';
import {Breadcrumb,CTA,PageHero} from '../../../components/shared';
import {Enquiry,Icon,ProductCard} from '../../../components/ui';
const tables={markets,materials,products,expertise,solutions,resources:articles};
type Section=keyof typeof tables;
export function generateStaticParams(){return Object.entries(tables).flatMap(([section,rows])=>rows.map(row=>({section,slug:row.slug})));}
export const dynamicParams=false;
export async function generateMetadata({params}:{params:Promise<{section:string,slug:string}>}):Promise<Metadata>{const {section,slug}=await params;const row=tables[section as Section]?.find(x=>x.slug===slug);if(!row)return {};const title='title' in row?row.title:row.name;const desc='summary' in row?row.summary:'intro' in row?row.intro:row.text;return {title,description:desc,alternates:{canonical:`/${section}/${slug}/`},openGraph:{title,description:desc,url:`/${section}/${slug}/`,type:section==='resources'?'article':'website'}};}
export default async function Detail({params}:{params:Promise<{section:string,slug:string}>}){const {section,slug}=await params;const row=tables[section as Section]?.find(x=>x.slug===slug);if(!row)notFound();const name='title' in row?row.title:row.name;const schema={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:origin},{'@type':'ListItem',position:2,name:section,item:`${origin}/${section}/`},{'@type':'ListItem',position:3,name,item:`${origin}/${section}/${slug}/`}]};const crumbs=[{name:section.charAt(0).toUpperCase()+section.slice(1),href:`/${section}/`},{name}];
 if(section==='products'){const p=products.find(x=>x.slug===slug)!;const related=products.filter(x=>x.marketSlug===p.marketSlug&&x.slug!==p.slug).slice(0,3);return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><div className="container"><Breadcrumb items={crumbs}/></div><section className="product-detail"><div className="detail-image"><img src={`/images/${p.image}.webp`} alt={`Illustrative generic ${p.name.toLowerCase()} application`}/><span>Illustrative concept · not an exact product photograph</span></div><div className="detail-copy"><Link className="eyebrow" href={`/markets/${p.marketSlug}/`}>{p.market} ↗</Link><h1>{p.name}</h1><p className="lead">{p.summary}</p><div className="spec-list"><div><span>Material options to discuss</span><strong>{p.material}</strong></div><div><span>Application</span><strong>{p.market}</strong></div><div><span>Specification</span><strong>Defined around your brief</strong></div></div><a className="button" href="#enquire">Build a project brief <Icon kind="arrow"/></a><p className="caption">Material grades, dimensions, availability and compliance are subject to supplier confirmation.</p></div></section><section className="section detail-body"><div><p className="eyebrow">APPLICATION CONSIDERATIONS</p><h2>Start with the complete picture.</h2><p>{p.application}</p><h3>What to include in your specification</h3><ul><li>Dimensions, interfaces and available space in the complete assembly.</li><li>Operating temperatures, handling conditions and anticipated loading.</li><li>Expected quantities, reuse cycle and recovery arrangements.</li><li>Relevant acceptance criteria and the evidence needed for approval.</li></ul><h3>From a family to a finished product</h3><p>This page introduces a product family. Final geometry, grade and processing route should be developed around the application. Request samples and a validation plan before making performance or suitability claims.</p></div><aside className="aside-box"><Icon kind="layers"/><h3>Material decisions matter.</h3><p>Review the options, then discuss the grade and design with a supplier.</p><Link href="/materials/">Explore materials →</Link><Link href={`/markets/${p.marketSlug}/`}>More in {p.market} →</Link></aside></section><section id="enquire" className="section enquiry-section"><div><p className="eyebrow">MAKE THE NEXT STEP USEFUL</p><h2>Your project.<br/>A clearer brief.</h2><p>Create a downloadable enquiry for this product family.</p></div><Enquiry product={p.name}/></section>{related.length>0&&<section className="section"><div className="section-heading"><h2>Related possibilities.</h2><Link href="/products/">All products →</Link></div><div className="product-grid">{related.map(r=><ProductCard key={r.slug} product={r}/>)}</div></section>}</>;}
 if(section==='markets'){const m=markets.find(x=>x.slug===slug)!;return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><div className="container"><Breadcrumb items={crumbs}/></div><PageHero eyebrow={`MARKET ${m.number} / ${m.name.toUpperCase()}`} title={`Possibilities for ${m.name.toLowerCase()}.`} text={m.intro} image={m.image}/><section className="section detail-body"><div><p className="eyebrow">BUILT AROUND THE APPLICATION</p><h2>Understand the need.<br/>Then shape the answer.</h2><p>{m.need}</p><p>Bring dimensions, operating conditions, assembly constraints and the expected service life into your brief. Compare candidate designs using representative samples and agreed acceptance criteria.</p></div><aside className="aside-box"><h3>Ask the right questions.</h3><p>What must the component protect, support or insulate? How will it be installed, transported and recovered?</p><Link href="/contact/">Create your project brief →</Link></aside></section><section className="section tight-top"><div className="section-heading"><h2>Explore product families.</h2><span>{m.products.length} application starting points</span></div><div className="product-grid">{products.filter(p=>p.marketSlug===m.slug).map(p=><ProductCard key={p.slug} product={p}/>)}</div></section><CTA/></>;}
 if(section==='resources'){const a=articles.find(x=>x.slug===slug)!;return <><div className="container"><Breadcrumb items={crumbs}/></div><PageHero eyebrow={`${a.category.toUpperCase()} / 3 MIN READ`} title={a.title} text={a.intro}/><article className="editorial article-body">{a.sections.map(([h,t])=><section key={h}><h2>{h}</h2><p>{t}</p></section>)}<aside className="article-note">This guide provides general design considerations. Confirm application suitability and test requirements with your supplier or technical adviser.</aside><Link className="button" href="/contact/">Turn this into a brief <Icon kind="arrow"/></Link></article><CTA/></>;}
 const v=(section==='materials'?materials:section==='expertise'?expertise:solutions).find(x=>x.slug===slug)!;return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><div className="container"><Breadcrumb items={crumbs}/></div><PageHero eyebrow={section.toUpperCase()} title={v.name} text={v.text} image={section==='materials'?'technical':undefined}/><section className="section detail-body"><div><p className="eyebrow">A PRACTICAL STARTING POINT</p><h2>{section==='materials'?'Choose around the application.':section==='expertise'?'Connect the process to the purpose.':'Define what a better result means.'}</h2><p>{'consider' in v?String(v.consider):'details' in v?String(v.details):'Start by documenting the existing design, the specific problem and how an improvement will be measured. Include operating conditions, assembly constraints and the intended service life.'}</p><h3>Questions to bring to the conversation</h3><ul><li>What is the application, and which requirements are essential?</li><li>How will the finished component be manufactured and assembled?</li><li>Which conditions should be represented in testing?</li><li>What happens at the end of the useful service life?</li></ul><p>Any performance, food-contact or environmental claim needs evidence for the specific grade and application. Agree the validation and documentation requirements before selecting a final design.</p></div><aside className="aside-box"><Icon kind="layers"/><h3>See the possibilities.</h3><p>Explore product families and industries to build a more specific brief.</p><Link href="/products/">Browse products →</Link><Link href="/markets/">Explore industries →</Link></aside></section><CTA/></>;}
