import ResponsiveImage from '../../components/ResponsiveImage';
import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {Breadcrumb,CTA,PageHero} from '../../components/shared';
import {Catalogue,Enquiry,Icon} from '../../components/ui';
import {markets,materials,expertise,solutions,articles} from '../../lib/catalog';
import {resourcePages,aboutPages} from '../../lib/resource-pages';
import {IndustryIndex} from '../../components/IndustryDetail';
const intro:Record<string,[string,string,string]>={products:['THE PRODUCT EXPLORER','Find the right starting point.','Explore protective packaging, insulation and technical components by market and material. Find product formats, application guidance and material selection priorities in one place.'],markets:['APPLICATIONS THAT SHAPE OUR THINKING','Different industries. Shared possibilities.','Explore Sports, Leisure & Early Childhood, Logistics & Material Handling, HVAC and Automotive, with product families and practical design considerations for each industry.'],materials:['A FOUNDATION FOR EVERY DESIGN','Material matters.','Understand the options before choosing the answer. Explore polymers, bead foams and circular material questions.'],expertise:['FROM CONCEPT TO COMPONENT','Make every design decision count.','Explore the manufacturing and development routes that connect an application brief to a finished component.'],solutions:['START WITH THE CHALLENGE','What does your product need to do?','A useful solution starts with a specific question. Explore the design challenges behind protection, thermal control, presentation and weight.'],resources:['THE KNOWLEDGE LIBRARY','A clearer view. A better brief.','Original practical guides to material selection, packaging development and the questions worth asking.'],about:['ABOUT PARKNONWOVEN EPP','An idea built around possibility.','Explore how better material decisions can lead to more considered products and packaging.'],contact:['YOUR NEXT STEP','Let’s start with your challenge.','Create a useful project brief with the information a materials or packaging supplier will need.'],privacy:['PRIVACY & TRANSPARENCY','Your information stays with you.','A plain-language overview of how this website handles information.']};
export function generateStaticParams(){return Object.keys(intro).map(section=>({section}));}
export const dynamicParams=false;
export async function generateMetadata({params}:{params:Promise<{section:string}>}):Promise<Metadata>{const {section}=await params;const v=intro[section];return {title:({products:'EPP Products & Protective Packaging',markets:'EPP Applications & Industries',materials:'Expanded Polypropylene Materials',expertise:'EPP Moulding Technology',contact:'Contact PARK EPP',about:'About PARK Nonwoven'} as Record<string,string>)[section]||v?.[1]||'Explore',description:v?.[2],alternates:{canonical:`/${section}/`}};}
export default async function Section({params}:{params:Promise<{section:string}>}){const {section}=await params;const info=intro[section];if(!info)notFound();return <><div className="container"><Breadcrumb items={[{name:section.charAt(0).toUpperCase()+section.slice(1)}]}/></div><PageHero eyebrow={info[0]} title={info[1]} text={info[2]} image={['about','expertise'].includes(section)?'technical':undefined}/><section className="section index-content">
 {section==='products'&&<Catalogue/>}
 {section==='markets'&&<IndustryIndex/>}
 {['materials','expertise','solutions'].includes(section)&&<div className="index-grid">{(section==='materials'?materials:section==='expertise'?expertise:solutions).map((v,i)=><Link href={`/${section}/${v.slug}/`} key={v.slug}><span className="index-number">{String(i+1).padStart(2,'0')}</span><Icon kind={section==='materials'?'layers':section==='expertise'?'box':'leaf'}/><h2>{v.name}</h2><p>{v.text}</p><span>Discover more →</span></Link>)}</div>}
 {section==='resources'&&<div className="index-grid">{resourcePages.map(a=><Link key={a.slug} href={`/resources/${a.slug}/`}><Icon kind="layers"/><h2>{a.title}</h2><p>{a.intro}</p><span>Explore resource ↗</span></Link>)}</div>}{section==='resources'&&<div className="article-grid">{articles.map((a,i)=><Link key={a.slug} href={`/resources/${a.slug}/`}><ResponsiveImage src={`/images/${['technical','packaging','food','technical'][i]}.webp`} alt=""/><div><p className="eyebrow">{a.category} · 3 MIN READ</p><h2>{a.title}</h2><p>{a.intro}</p><span>Read guide →</span></div></Link>)}</div>}
 {section==='about'&&<><div className="editorial"><p className="eyebrow">THE IDEA</p><h2>Materials are only the beginning.</h2><p>What matters is what a component makes possible: a product protected on its journey, a thoughtfully insulated system, or a form that uses space more effectively. This site organises those possibilities around industries, materials and development decisions.</p><p>The PARK EPP and engineered-materials range focuses on four industries: Sports, Leisure & Early Childhood, Logistics & Material Handling, HVAC and Automotive. Each family brings together a material starting point and the design priorities worth discussing.</p><h2>A considered way to explore.</h2><p>Start with an industry or a design challenge, then compare material and manufacturing options. Each product family includes questions to help build a useful brief for a real supplier. Bring your drawings and application requirements into the conversation to develop the right specification.</p></div><div className="process-grid">{['Define the application','Compare the options','Validate the design','Plan the next life'].map((s,i)=><div key={s}><span>0{i+1}</span><h3>{s}</h3><p>{['Understand the operating conditions and the problem to solve.','Bring material, process and assembly requirements together.','Agree a test plan and measurable acceptance criteria.','Consider reuse, separation and local recovery arrangements.'][i]}</p></div>)}</div></>}
 {section==='contact'&&<div className="contact-grid"><aside><p className="eyebrow">A GOOD BRIEF INCLUDES</p><h2>Bring your questions.<br/>And a few details.</h2><ul>{['The application and operating environment','Drawings, dimensions and assembly interfaces','Expected volumes and project timeline','Material, food-contact or testing requirements','Packaging route and recovery arrangements'].map(x=><li key={x}><Icon kind="check"/>{x}</li>)}</ul><p>Create your project brief below, then email it with your drawings to sales@parknonwoven.com.</p></aside><Enquiry/></div>}
 {section==='privacy'&&<div className="editorial"><h2>Project enquiry form</h2><p>Your entries are processed in your browser to create a downloadable text file. They are not submitted to a server, stored in a database or sent by email. Protect the downloaded file if it includes confidential project details.</p><h2>Browsing</h2><p>This application does not install analytics, advertising trackers or application cookies. The hosting provider may process standard technical request information to deliver the website and manage access.</p><h2>Illustrative content</h2><p>This website presents illustrative product families. Images are AI-generated illustrations of generic industrial applications. No affiliation with another manufacturer is implied. Product specifications, availability, regulatory suitability and commercial terms require confirmation from a real supplier.</p><h2>Contact details</h2><p>For enquiries about this website or project information, contact sales@parknonwoven.com.</p></div>}
 </section>{!['contact','privacy'].includes(section)&&<CTA/>}</>;}
