import Link from 'next/link';
import {Film,Icon,ProductCard} from '../components/ui';
import {CTA} from '../components/shared';
import {markets,products,materials,expertise,solutions,articles} from '../lib/catalog';
export default function Home(){return <>
 <section className="hero"><img className="hero-photo" src="/images/hero.webp" alt="Original studio composition of foam packaging, technical components and a food tray" fetchPriority="high"/><div className="hero-content"><p className="eyebrow"><span className="blue-line"/>ENGINEERING WHAT COMES NEXT</p><h1>Less weight.<br/>More <span>possibility.</span></h1><p>Intelligent packaging. Lightweight components.<br/>Materials that move your ideas forward.</p><div className="hero-buttons"><Link className="button" href="/products/">Discover our solutions <Icon kind="arrow"/></Link><Film/></div></div><div className="hero-caption"><span>01 / MATERIAL THINKING</span><span>Protection. Performance. Possibility.</span></div></section>
 <div className="intro-strip"><span>FROM MATERIAL TO MEANINGFUL SOLUTIONS</span><div><Icon kind="box"/>Protect better</div><div><Icon kind="layers"/>Build lighter</div><div><Icon kind="leaf"/>Think circular</div><a href="#markets" aria-label="Explore markets below">↓</a></div>
 <section className="section markets-section" id="markets"><div className="section-heading"><div><p className="eyebrow">YOUR INDUSTRY. OUR STARTING POINT.</p><h2>Every industry has a challenge.<br/><span>Let’s find its solution.</span></h2></div><p>From the food we share to the spaces we live in, explore materials and product families shaped around the way your industry works.</p></div><div className="market-grid">{markets.map((m,i)=><Link key={m.slug} href={`/markets/${m.slug}/`} className={`market-card ${i===0?'market-feature':''}`}><img src={`/images/${m.image}.webp`} alt="" loading="lazy"/><div className="market-overlay"/><div className="market-info"><span className="market-number">{m.number}</span><h3>{m.name}</h3><p>{m.intro}</p><span className="market-arrow">↗</span></div></Link>)}</div></section>
 <section className="solutions-section section"><div className="section-heading"><div><p className="eyebrow">START WITH WHAT MATTERS</p><h2>Better by design.</h2></div><Link className="text-link" href="/solutions/">Explore every challenge <Icon kind="arrow"/></Link></div><div className="solution-grid">{solutions.slice(0,6).map((s,i)=><Link key={s.slug} href={`/solutions/${s.slug}/`}><Icon kind={['layers','leaf','box','shield','snow','box'][i]}/><h3>{s.name}</h3><p>{s.text}</p><span>Explore solution ↗</span></Link>)}</div></section>
 <section className="section"><div className="section-heading"><div><p className="eyebrow">A CLOSER LOOK</p><h2>Small details.<br/><span>A world of applications.</span></h2></div><Link className="text-link" href="/products/">Browse the catalogue <Icon kind="arrow"/></Link></div><div className="product-grid">{[products.find(p=>p.name==='Stackable delivery boxes')!,products.find(p=>p.name==='Custom HVAC components')!,products.find(p=>p.name==='Custom food packaging')!].map(p=><ProductCard key={p.slug} product={p}/>)}</div></section>
 <section className="material-feature"><div className="material-visual"><img src="/images/technical.webp" alt="Illustrative foam and injection moulded engineering components" loading="lazy"/><div className="material-label"><span>FORM FOLLOWS FUNCTION.</span><strong>Material<br/>possibilities.</strong></div></div><div className="material-content"><p className="eyebrow">THE RIGHT MATERIAL CHANGES EVERYTHING</p><h2>Choose with purpose.<br/>Create with confidence.</h2><p>There is no single answer to every application. Explore material options around performance, processing and the journey after use.</p><div className="material-list">{materials.map(m=><Link key={m.slug} href={`/materials/${m.slug}/`}><span>{m.short}</span>{m.name}<Icon kind="arrow"/></Link>)}</div></div></section>
 <section className="section"><div className="section-heading"><div><p className="eyebrow">FROM A QUESTION TO A COMPONENT</p><h2>Ideas, made tangible.</h2></div><p>A clear development path brings design, materials and validation into the same conversation.</p></div><div className="process-grid">{expertise.slice(0,4).map((e,i)=><Link key={e.slug} href={`/expertise/${e.slug}/`}><span>0{i+1}</span><h3>{e.name}</h3><p>{e.text}</p><Icon kind="arrow"/></Link>)}</div></section>
 <section className="thinking-banner"><div><Icon kind="leaf"/><p className="eyebrow">CIRCULAR THINKING STARTS EARLY</p><h2>A better next life<br/>starts with a better first design.</h2><p>Material efficiency, thoughtful reuse and accessible recovery routes belong in the brief from day one.</p><Link className="button light" href="/resources/design-for-reuse/">Explore design for reuse <Icon kind="arrow"/></Link></div><div className="orbit" aria-hidden="true"><span>DESIGN</span><span>USE</span><span>RECOVER</span><span>RETHINK</span><Icon kind="leaf"/></div></section>
 <section className="section"><div className="section-heading"><div><p className="eyebrow">KNOWLEDGE TO MOVE YOU FORWARD</p><h2>A little insight.<br/><span>A better starting point.</span></h2></div><Link className="text-link" href="/resources/">All insights <Icon kind="arrow"/></Link></div><div className="article-grid">{articles.slice(0,3).map((a,i)=><Link key={a.slug} href={`/resources/${a.slug}/`}><img src={`/images/${['technical','packaging','food'][i]}.webp`} alt="" loading="lazy"/><div><p className="eyebrow">{a.category} · 3 MIN READ</p><h3>{a.title}</h3><span>Read the guide ↗</span></div></Link>)}</div></section><CTA/>
 </>;}
