import Link from 'next/link';
import {eppOverview, eppProperties, eppManufacturingSteps, eppSelectionChecklist, eppComparison, eppApplications, eppFaqs, eppSources} from '../lib/epp-education';
import {BeadStructure} from './EppKnowledge';
import {Icon} from './ui';
import styles from './EppEducation.module.css';

function References({ids}: {ids: readonly string[]}) {
  const sources = eppSources.filter(source => ids.includes(source.id));
  if (!sources.length) return null;
  return <span className={styles.references}>{sources.map(source => <a href={source.url} key={source.id} target="_blank" rel="noopener noreferrer" aria-label={`Technical reference: ${source.title}`}>{source.organisation} ↗</a>)}</span>;
}

export default function EppMaterialGuide() {
  return <div className={styles.guide}>
    <nav className={styles.contents} aria-label="EPP guide topics">{[['properties', 'Material properties'], ['manufacturing', 'How it is made'], ['applications', 'Applications'], ['comparison', 'EPP vs EPS'], ['design', 'Design & selection'], ['faq', 'FAQs']].map(([id, label]) => <a key={id} href={`#epp-${id}`}>{label} <span>↘</span></a>)}</nav>
    <section className={styles.overview} aria-labelledby="epp-overview-heading"><div><p className="eyebrow">THE MATERIAL, EXPLAINED</p><h2 id="epp-overview-heading">What is expanded polypropylene?</h2><p>{eppOverview.summary}</p><p>{eppOverview.detail}</p><Link className={styles.inlineLink} href="/#industry-heading">Explore our four industries <Icon kind="arrow"/></Link></div><BeadStructure/></section>
    <section id="epp-properties" className={styles.guideSection} aria-labelledby="epp-properties-heading"><div className={styles.heading}><div><p className="eyebrow">WHY EPP?</p><h2 id="epp-properties-heading">Properties that work together.</h2></div><p>Choose the grade, density and geometry around the job the finished component needs to do.</p></div><div className={styles.properties}>{eppProperties.map((item, i) => <article key={item.id}><span className={styles.propertyNumber}>0{i + 1}</span><h3>{item.title}</h3><p>{item.benefit}</p><p className={styles.consideration}>{item.consideration}</p><References ids={item.sourceIds}/></article>)}</div></section>
    <section id="epp-manufacturing" className={styles.guideSection} aria-labelledby="epp-manufacturing-heading"><div className={styles.heading}><div><p className="eyebrow">FROM BEAD TO COMPONENT</p><h2 id="epp-manufacturing-heading">How EPP takes its shape.</h2></div><Link className={styles.inlineLink} href="/">Watch the process on our homepage <Icon kind="arrow"/></Link></div><ol className={styles.manufacturing}>{eppManufacturingSteps.map((item, i) => <li key={item.title}><span>0{i + 1}</span><h3>{item.title}</h3><p>{item.description}</p><References ids={item.sourceIds}/></li>)}</ol></section>
    <section id="epp-applications" className={styles.guideSection} aria-labelledby="epp-applications-guide-heading"><div className={styles.heading}><div><p className="eyebrow">FOUR INDUSTRIES. MANY USES.</p><h2 id="epp-applications-guide-heading">Where does EPP fit?</h2></div></div><div className={styles.applicationList}>{eppApplications.map(item => <article key={item.slug}><div><h3><Link href={`/markets/${item.slug}/`}>{item.title} <span>↗</span></Link></h3><p>{item.summary}</p><p className={styles.examples}>{item.examples.join(' · ')}</p></div><div><h4>Design focus</h4><p>{item.designFocus}</p><References ids={item.sourceIds}/></div></article>)}</div></section>
    <section id="epp-comparison" className={styles.guideSection} aria-labelledby="epp-comparison-heading"><div className={styles.heading}><div><p className="eyebrow">MATERIAL SELECTION</p><h2 id="epp-comparison-heading">EPP and EPS, side by side.</h2></div><p>Start with the application, then compare representative parts under the same conditions.</p></div><div className={styles.tableWrap} role="region" aria-label="EPP and EPS comparison" tabIndex={0}><table className={styles.comparison}><thead><tr><th scope="col">Consideration</th><th scope="col">EPP · Expanded polypropylene</th><th scope="col">EPS · Expanded polystyrene</th></tr></thead><tbody>{eppComparison.map(row => <tr key={row.topic}><th scope="row">{row.topic}<References ids={row.sourceIds}/></th><td>{row.epp}</td><td>{row.eps}</td></tr>)}</tbody></table></div></section>
    <section id="epp-design" className={styles.guideSection} aria-labelledby="epp-design-heading"><div className={styles.heading}><div><p className="eyebrow">A BETTER DESIGN BRIEF</p><h2 id="epp-design-heading">Specify the whole component.</h2></div><p>Bring these details into the conversation before selecting a material grade or committing to tooling.</p></div><ol className={styles.checklist}>{eppSelectionChecklist.map((item, i) => <li key={item.title}><span>{String(i + 1).padStart(2, '0')}</span><div><h3>{item.title}</h3><p>{item.detail}</p><References ids={item.sourceIds}/></div></li>)}</ol><Link className="button compact" href="/contact/">Discuss your EPP application <Icon kind="arrow"/></Link></section>
    <section id="epp-faq" className={styles.guideSection} aria-labelledby="epp-faq-heading"><div className={styles.heading}><div><p className="eyebrow">GOOD QUESTIONS. CLEAR ANSWERS.</p><h2 id="epp-faq-heading">More about EPP.</h2></div></div><div className={styles.faq}>{eppFaqs.map(item => <details key={item.question}><summary>{item.question}<Icon kind="close"/></summary><div><p>{item.answer}</p><References ids={item.sourceIds}/></div></details>)}</div></section>
    <section id="epp-sources" className={styles.sources} aria-labelledby="epp-sources-heading"><h2 id="epp-sources-heading">Further technical reading</h2><p>Material manufacturer references support this guide. Check the documentation for your selected grade when developing a specification.</p><ul>{eppSources.map(source => <li key={source.id}><a href={source.url} target="_blank" rel="noopener noreferrer">{source.title} <span>↗</span></a><span>{source.organisation}</span></li>)}</ul></section>
  </div>;
}
