import Link from 'next/link';
import {eppOverview, eppProperties, eppManufacturingSteps, eppSelectionChecklist, eppApplications, eppFaqs} from '../lib/epp-education';
import {BeadStructure} from './EppKnowledge';
import {Icon} from './ui';
import styles from './EppEducation.module.css';

export default function EppMaterialGuide() {
  return <div className={styles.guide}>
    <nav className={styles.contents} aria-label="EPP guide topics">{[['properties', 'Material properties'], ['manufacturing', 'How it is made'], ['applications', 'Applications'], ['design', 'Design & selection'], ['faq', 'FAQs']].map(([id, label]) => <a key={id} href={`#epp-${id}`}>{label} <span>↘</span></a>)}</nav>
    <section className={styles.overview} aria-labelledby="epp-overview-heading"><div><p className="eyebrow">THE MATERIAL, EXPLAINED</p><h2 id="epp-overview-heading">What is expanded polypropylene?</h2><p>{eppOverview.summary}</p><p>{eppOverview.detail}</p><Link className={styles.inlineLink} href="/#industry-heading">Explore our four industries <Icon kind="arrow"/></Link></div><BeadStructure/></section>
    <section id="epp-properties" className={styles.guideSection} aria-labelledby="epp-properties-heading"><div className={styles.heading}><div><p className="eyebrow">WHY EPP?</p><h2 id="epp-properties-heading">Properties that work together.</h2></div><p>Choose the grade, density and geometry around the job the finished component needs to do.</p></div><div className={styles.properties}>{eppProperties.map((item, i) => <article key={item.id}><span className={styles.propertyNumber}>0{i + 1}</span><h3>{item.title}</h3><p>{item.benefit}</p><p className={styles.consideration}>{item.consideration}</p></article>)}</div></section>
    <section id="epp-manufacturing" className={styles.guideSection} aria-labelledby="epp-manufacturing-heading"><div className={styles.heading}><div><p className="eyebrow">FROM BEAD TO COMPONENT</p><h2 id="epp-manufacturing-heading">How EPP takes its shape.</h2></div><Link className={styles.inlineLink} href="/">Watch the process on our homepage <Icon kind="arrow"/></Link></div><ol className={styles.manufacturing}>{eppManufacturingSteps.map((item, i) => <li key={item.title}><span>0{i + 1}</span><h3>{item.title}</h3><p>{item.description}</p></li>)}</ol></section>
    <section id="epp-applications" className={styles.guideSection} aria-labelledby="epp-applications-guide-heading"><div className={styles.heading}><div><p className="eyebrow">FOUR INDUSTRIES. MANY USES.</p><h2 id="epp-applications-guide-heading">Where does EPP fit?</h2></div></div><div className={styles.applicationList}>{eppApplications.map(item => <article key={item.slug}><div><h3><Link href={`/markets/${item.slug}/`}>{item.title} <span>↗</span></Link></h3><p>{item.summary}</p><p className={styles.examples}>{item.examples.join(' · ')}</p></div><div><h4>Design focus</h4><p>{item.designFocus}</p></div></article>)}</div></section>
    <section id="epp-design" className={styles.guideSection} aria-labelledby="epp-design-heading"><div className={styles.heading}><div><p className="eyebrow">A BETTER DESIGN BRIEF</p><h2 id="epp-design-heading">Specify the whole component.</h2></div><p>Bring these details into the conversation before selecting a material grade or committing to tooling.</p></div><ol className={styles.checklist}>{eppSelectionChecklist.map((item, i) => <li key={item.title}><span>{String(i + 1).padStart(2, '0')}</span><div><h3>{item.title}</h3><p>{item.detail}</p></div></li>)}</ol><Link className="button compact" href="/contact/">Discuss your EPP application <Icon kind="arrow"/></Link></section>
    <section id="epp-faq" className={styles.guideSection} aria-labelledby="epp-faq-heading"><div className={styles.heading}><div><p className="eyebrow">GOOD QUESTIONS. CLEAR ANSWERS.</p><h2 id="epp-faq-heading">More about EPP.</h2></div></div><div className={styles.faq}>{eppFaqs.map(item => <details key={item.question}><summary>{item.question}<Icon kind="close"/></summary><div><p>{item.answer}</p></div></details>)}</div></section>
    <section id="epp-project" className={styles.projectBrief} aria-labelledby="epp-project-heading"><div><p className="eyebrow">YOUR APPLICATION. YOUR REQUIREMENTS.</p><h2 id="epp-project-heading">Bring your EPP brief to PARK.</h2><p>Share your drawing, working environment and expected loads. Use the selected grade documentation and representative-part tests to define the requirements for your project.</p></div><Link className="button compact" href="/contact/">Discuss your project <Icon kind="arrow"/></Link></section>
  </div>;
}
