'use client';
import ResponsiveImage from './ResponsiveImage';
import Link from 'next/link';
import {useEffect, useRef, useState} from 'react';
import {markets} from '../lib/catalog';
const industryImages = ['/images/markets/sports.webp', '/images/markets/logistics.webp', '/images/markets/hvac.webp', '/images/markets/mobility.webp'];
import {Icon} from './ui';
const slides = [
 {'title': 'Food packed for the journey.', 'text': 'From fresh meals to catering, plan protective and insulated transport around the food, handling and delivery route.', 'image': '/images/use-food-packing.webp', 'video': '/videos/use-food-packing-fast-v1.mp4', 'mobileVideo': '/videos/use-food-packing-mobile-fast-v1.mp4', 'href': '/solutions/manage-temperature/', 'action': 'Explore food transport'},
 {'title': 'From kitchen to doorstep.', 'text': 'Insulated EPP transport containers can form part of a delivery system designed around payload, journey time and temperature needs.', 'image': '/images/use-food-delivery.webp', 'video': '/videos/use-food-delivery-fast-v1.mp4', 'mobileVideo': '/videos/use-food-delivery-mobile-fast-v1.mp4', 'href': '/solutions/manage-temperature/', 'action': 'Explore insulated transport'},
 {'title': 'Protection through every handover.', 'text': 'Fitted foam inserts and reusable packs are developed around loading, storage, transport and repeated handling.', 'image': '/images/use-logistics.webp', 'video': '/videos/use-logistics-fast-v1.mp4', 'mobileVideo': '/videos/use-logistics-mobile-fast-v1.mp4', 'href': '/markets/logistics-handling/', 'action': 'Explore logistics'},
 {'title': 'Part of the everyday journey.', 'text': 'Explore lightweight foam components for vehicle interiors, impact management and assembly integration.', 'image': '/images/use-automotive.webp', 'video': '/videos/use-automotive-fast-v1.mp4', 'mobileVideo': '/videos/use-automotive-mobile-fast-v1.mp4', 'href': '/markets/mobility/', 'action': 'Explore automotive'},
 {'title': 'Made for movement and play.', 'text': 'Discover lightweight foam forms for training equipment, recreation and early-childhood activities.', 'image': '/images/use-sports.webp', 'video': '/videos/use-sports-fast-v1.mp4', 'mobileVideo': '/videos/use-sports-mobile-fast-v1.mp4', 'href': '/markets/sports-leisure/', 'action': 'Explore sports and play'},
];
export default function EppShowcase(){
 const [active,setActive]=useState(0),[paused,setPaused]=useState(false),[interacting,setInteracting]=useState(false),[reduced,setReduced]=useState(true);
 const [saveData,setSaveData]=useState(false);
 const [visible,setVisible]=useState(false),[ready,setReady]=useState(false);
 const video=useRef<HTMLVideoElement>(null),root=useRef<HTMLDivElement>(null);
 useEffect(()=>{setSaveData(Boolean((navigator as Navigator & {connection?:{saveData?:boolean}}).connection?.saveData));const preference=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setReduced(preference.matches);update();preference.addEventListener('change',update);const header=document.querySelector('header');const fit=()=>root.current?.style.setProperty('--showcase-header',`${header?.getBoundingClientRect().bottom || 100}px`);const observer=new ResizeObserver(fit);if(header)observer.observe(header);fit();return()=>{preference.removeEventListener('change',update);observer.disconnect();};},[]);
 useEffect(()=>{const observer=new IntersectionObserver(([entry])=>setVisible(entry.isIntersecting),{threshold:0.1});if(root.current)observer.observe(root.current.querySelector('.park-banner')||root.current);return()=>observer.disconnect();},[]);
 useEffect(()=>{setReady(false);},[active]);
 useEffect(()=>{if(paused||reduced||interacting||!visible||saveData)return;const timer=setInterval(()=>{if(!document.hidden)setActive(value=>(value+1)%slides.length);},8500);return()=>clearInterval(timer);},[paused,reduced,interacting,visible,saveData]);
 useEffect(()=>{const update=()=>{if(paused||reduced||!visible||document.hidden)video.current?.pause();else void video.current?.play().catch(()=>{});};update();document.addEventListener('visibilitychange',update);return()=>document.removeEventListener('visibilitychange',update);},[paused,reduced,active,visible,saveData]);
 const slide=slides[active];const move=(direction:number)=>setActive(value=>(value+direction+slides.length)%slides.length);
 return <div ref={root} className="home-showcase"><section className="park-banner" aria-label="PARK EPP highlights" aria-roledescription="carousel" onMouseEnter={()=>setInteracting(true)} onMouseLeave={()=>setInteracting(false)} onFocusCapture={()=>setInteracting(true)} onBlurCapture={event=>{if(!event.currentTarget.contains(event.relatedTarget))setInteracting(false);}}>
 <ResponsiveImage className="park-banner-video" src={slide.image} alt="" sizes="100vw" fetchPriority={active===0?'high':'auto'}/>{visible&&!reduced&&!saveData&&<video key={slide.video} ref={video} className="park-banner-video" style={{opacity:ready?1:0}} muted loop playsInline preload="none" onCanPlay={()=>setReady(true)} aria-hidden="true"><source src={slide.mobileVideo} media="(max-width:760px)" type="video/mp4"/><source src={slide.video} type="video/mp4"/></video>}<div className="park-banner-panel"/><div className="park-banner-copy" aria-live={paused||interacting?'polite':'off'}><span className="park-banner-eyebrow"><span/>PARK / EPP APPLICATIONS</span><div className="epp-banner-tagline">Future of light weight</div><h1>{slide.title}</h1><p>{slide.text}</p><Link href={slide.href} className="park-banner-link">{slide.action}<Icon kind="arrow"/></Link></div><div className="park-banner-arrows"><span className="park-banner-count">{String(active+1).padStart(2,'0')}<span> / {String(slides.length).padStart(2,'0')}</span></span><button onClick={()=>move(-1)} aria-label="Previous banner">‹</button><button onClick={()=>move(1)} aria-label="Next banner">›</button></div></section>
 <div className="park-banner-controls"><div className="park-banner-dots">{slides.map((item,index)=><button key={item.title} aria-label={`Show banner ${index+1}: ${item.title}`} aria-pressed={active===index} onClick={()=>setActive(index)}><span/></button>)}</div><button className="park-banner-pause" onClick={()=>setPaused(value=>!value)} aria-label={paused?'Play slideshow and film':'Pause slideshow and film'}><Icon kind={paused?'play':'pause'}/></button></div>
 <section id="industries" className="park-industry-shortcuts" aria-labelledby="industry-shortcuts-title"><span className="park-industry-kicker">FIND YOUR INDUSTRY</span><h2 id="industry-shortcuts-title">Lightweight solutions for every application</h2><p>Protection. Insulation. Possibilities shaped around you.</p><div className="park-industry-cards">{markets.map((market,index)=>{return <Link key={market.slug} href={`/markets/${market.slug}/`} className="park-industry-card"><ResponsiveImage src={industryImages[index]} alt={`${market.name} application illustration`} loading="lazy"/><span className="park-industry-number">0{index+1}</span><div className="park-industry-card-copy"><h3>{market.name}</h3><span className="park-industry-discover">Explore solutions<span className="park-industry-arrow"><Icon kind="arrow"/></span></span></div></Link>;})}</div></section></div>;
}
