'use client';
import Link from 'next/link';
import {useRef,useState,useEffect} from 'react';
import {markets,products,materials,expertise,solutions,articles} from '../lib/catalog';
import {marketImagePath} from '../lib/navigation';
import {marketGuides} from '../lib/content';
import {Catalogue,Enquiry,Film,Icon} from './ui';
export default function Home(){const [industry,setIndustry]=useState(3),[paused,setPaused]=useState(false);const video=useRef<HTMLVideoElement>(null);const m=markets[industry];useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches){video.current?.pause();setPaused(true);}},[]);return <>
<section className="park-hero"><video ref={video} autoPlay muted loop playsInline poster="/images/markets/forest.webp" aria-hidden="true"><source src="/videos/park-materials-hero.mp4" type="video/mp4"/></video><div className="park-hero-shade"/><div className="park-hero-content"><p className="eyebrow">PARK NONWOVEN · EPP & ENGINEERED MATERIALS</p><h1>Lightweight by design.<br/><span>Made for your needs.</span></h1><p>From protective packaging to precision components, discover material possibilities built around your product, your industry and its next journey.</p><div className="hero-buttons"><Link className="button light" href="/products/">Explore our products <Icon kind="arrow"/></Link><Link className="park-white-link" href="/markets/">Find your industry ↗</Link></div></div><div className="park-hero-bottom"><a href="#discover">Discover the possibilities ↓</a><button onClick={()=>{if(paused)void video.current?.play();else video.current?.pause();setPaused(!paused);}}><Icon kind={paused?'play':'pause'}/>{paused?'Play film':'Pause film'}</button></div></section>
<div className="park-benefits">{[['layers','Lightweight material thinking'],['shield','Protection shaped to fit'],['leaf','A considered next life']].map(([icon,text])=><div key={text}><Icon kind={icon}/><span>{text}</span></div>)}</div>
<section id="discover" className="section park-intro"><div><p className="eyebrow">FROM MATERIAL TO POSSIBILITY</p><h2>Small in weight.<br/><span>Big in possibilities.</span></h2></div><div><p>Every product has a different job to do. It might protect a delicate surface, manage temperature, support an assembly or carry fresh food to its destination. The right starting point connects the material with the complete application.</p><p>Explore EPP, EPS, rigid polymers and cellular foam through an extensive catalogue of packaging and engineered product families.</p><div className="park-stats"><div><strong>13</strong><span>industry applications</span></div><div><strong>{products.length}</strong><span>product families</span></div><div><strong>{materials.length}</strong><span>material guides</span></div></div><Link className="text-link" href="/about/">Discover PARK material thinking <Icon kind="arrow"/></Link></div></section>
<section className="section pale"><div className="section-heading"><div><p className="eyebrow">YOUR INDUSTRY. YOUR POSSIBILITIES.</p><h2>Shaped around your world.</h2></div><Link className="text-link" href="/markets/">Explore all markets <Icon kind="arrow"/></Link></div><div className="park-industry"><div className="park-industry-list" role="tablist" aria-label="Industry applications">{markets.map((x,i)=><button role="tab" aria-selected={industry===i} key={x.slug} onClick={()=>setIndustry(i)}><span>{x.number}</span>{x.name}<Icon kind="arrow"/></button>)}</div><div className="park-industry-visual" role="tabpanel" aria-label={m.name}><img src={marketImagePath(m.slug)} alt={`${m.name} material application`} loading="lazy"/><div><p className="eyebrow">{m.name}</p><h3>{m.intro}</h3><Link className="button light" href={`/markets/${m.slug}/`}>Explore {m.name} <Icon kind="arrow"/></Link></div></div></div><div className="park-application-chips">{marketGuides[m.slug]?.applications.map(x=><Link key={x} href={`/markets/${m.slug}/`}>{x} ↗</Link>)}</div></section>
<section className="section"><div className="section-heading"><div><p className="eyebrow">OUR PRODUCT RANGE</p><h2>The right shape for your next idea.</h2></div><p>Browse by industry, material or product. Discover the design priorities behind each family.</p></div><Catalogue compact/><div className="park-center"><Link className="button" href="/products/">Explore all {products.length} product families <Icon kind="arrow"/></Link></div></section>
<section className="park-technical"><div className="park-technical-image"><img src="/images/markets/hvac.webp" alt="Engineered foam HVAC components" loading="lazy"/><div><p className="eyebrow">PRECISION MEETS POSSIBILITY</p><h2>More than a material.<br/>Part of your design.</h2></div></div><div className="park-technical-copy"><p className="eyebrow">OUR EXPERTISE</p><h2>From your drawing.<br/>To a considered component.</h2><p>Bring geometry, operating conditions and assembly together. Explore manufacturing routes that help turn an application brief into a practical design.</p>{expertise.slice(0,4).map((x,i)=><Link key={x.slug} href={`/expertise/${x.slug}/`}><span>0{i+1}</span><div><h3>{x.name}</h3><p>{x.text}</p></div><Icon kind="arrow"/></Link>)}<Link className="text-link" href="/expertise/">All manufacturing & development expertise ↗</Link></div></section>
<section className="section"><div className="section-heading"><div><p className="eyebrow">MATERIAL THINKING</p><h2>A foundation for every design.</h2></div><p>Compare structure, processing and application requirements before selecting a grade.</p></div><div className="park-material-grid">{materials.map((x,i)=><Link key={x.slug} href={`/materials/${x.slug}/`}><span className="park-material-number">0{i+1}</span><Icon kind="layers"/><h3>{x.name}</h3><p>{x.text}</p><span className="text-link">Explore material ↗</span></Link>)}</div></section>
<section className="section pale"><div className="section-heading"><div><p className="eyebrow">START WITH THE CHALLENGE</p><h2>What should your product make possible?</h2></div><Link className="text-link" href="/solutions/">Explore solutions ↗</Link></div><div className="solution-grid">{solutions.map(x=><Link key={x.slug} href={`/solutions/${x.slug}/`}><Icon kind="leaf"/><h3>{x.name}</h3><p>{x.text}</p><span>Explore the approach ↗</span></Link>)}</div></section>
<section className="section"><div className="section-heading"><div><p className="eyebrow">YOUR PROJECT. A CLEARER PATH.</p><h2>Good questions lead to better components.</h2></div></div><div className="process-grid">{[['Define the application','Share the operating environment, geometry, interfaces and the problem you want to solve.'],['Compare the options','Bring candidate materials, manufacturing processes and assembly requirements into the same review.'],['Validate the design','Use representative samples and agree measurable criteria for fit, handling and performance.'],['Plan the next life','Consider cleaning, reuse, separation and recovery alongside the original product design.']].map(([h,p],i)=><div key={h}><span>0{i+1}</span><h3>{h}</h3><p>{p}</p></div>)}</div></section>
<section className="park-circular"><img src="/images/markets/forest.webp" alt="Sunlit green forest" loading="lazy"/><div><p className="eyebrow">RESPONSIBLE BY DESIGN</p><h2>Think beyond the first journey.</h2><p>Material choices connect to product life, return routes and recovery. Explore practical ways to build those questions into your project from the beginning.</p><Link className="button light" href="/about/responsible-design/">Explore responsible design <Icon kind="arrow"/></Link></div></section>
<section className="section"><div className="section-heading"><div><p className="eyebrow">INSIGHTS & RESOURCES</p><h2>Fresh thinking. Practical guidance.</h2></div><Link className="text-link" href="/resources/">All resources ↗</Link></div><div className="article-grid">{articles.slice(0,3).map((a,i)=><Link key={a.slug} href={`/resources/${a.slug}/`}><img src={marketImagePath(markets[[0,5,8][i]].slug)} alt="" loading="lazy"/><div><p className="eyebrow">{a.category}</p><h3>{a.title}</h3><p>{a.intro}</p><span>Read guide ↗</span></div></Link>)}</div><div className="park-download"><div><p className="eyebrow">PRODUCT CATALOGUE & FILM</p><h3>Take the possibilities with you.</h3><p>Explore the full product-family catalogue and our material story.</p></div><a className="button" href="/downloads/park-nonwoven-epp-catalogue.pdf" download>Download catalogue <Icon kind="download"/></a><Film/></div></section>
<section className="section pale contact-grid"><aside><p className="eyebrow">LET’S TALK</p><h2>Your next idea<br/>starts here.</h2><p>Tell us what your product needs to do. Bring your drawings, dimensions, planned quantities and the challenge you want to solve.</p><a className="text-link" href="mailto:sales@parknonwoven.com">sales@parknonwoven.com ↗</a></aside><Enquiry/></section></>;}
