import Link from 'next/link';
import {Icon} from './ui';
import {Brand} from './Header';
import {brand,markets,expertise,materials} from '../lib/catalog';
import {resourceLinks,aboutLinks} from '../lib/navigation';
export function Footer(){return <footer className="park-footer"><div className="park-footer-intro"><Brand/><div><h2>Material possibilities.<br/>Made around your needs.</h2><p>EPP & EPS components · Protective packaging · Engineered polymer solutions</p></div><a href="mailto:sales@parknonwoven.com" className="button light">Talk to PARK <Icon kind="arrow"/></a></div><div className="park-footer-columns"><div><h3>Markets</h3>{markets.map(m=><Link key={m.slug} href={`/markets/${m.slug}/`}>{m.name}</Link>)}</div><div><h3>Our expertise</h3>{expertise.map(e=><Link key={e.slug} href={`/expertise/${e.slug}/`}>{e.name}</Link>)}</div><div><h3>Materials</h3>{materials.map(m=><Link key={m.slug} href={`/materials/${m.slug}/`}>{m.name}</Link>)}</div><div><h3>Resources</h3>{resourceLinks.map(l=><Link key={l.href} href={l.href}>{l.name}</Link>)}<h3 className="footer-subtitle">About PARK</h3>{aboutLinks.map(l=><Link key={l.href} href={l.href}>{l.name}</Link>)}</div></div><div className="park-footer-bottom"><span>© {new Date().getFullYear()} {brand}. All rights reserved.</span><Link href="/privacy/">Privacy & information</Link><a href="mailto:sales@parknonwoven.com">sales@parknonwoven.com ↗</a></div></footer>;}
export function CTA(){return <section className="cta"><div><p className="eyebrow">FROM YOUR APPLICATION TO A CLEARER SPECIFICATION</p><h2>Tell us what you need.<br/>Let’s explore the possibilities.</h2></div><div><p>Share your drawing, dimensions or current packaging.<br/>Start a practical conversation about the right format.</p><Link className="button" href="/contact/">Discuss your requirement <Icon kind="arrow"/></Link><a className="cta-email" href="mailto:sales@parknonwoven.com">sales@parknonwoven.com ↗</a></div></section>;}
export function Breadcrumb({items}:{items:{name:string,href?:string}[]}){return <nav className="breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link>{items.map((x,i)=><span key={i}> / {x.href?<Link href={x.href}>{x.name}</Link>:<span aria-current="page">{x.name}</span>}</span>)}</nav>;}
export function PageHero({eyebrow,title,text,image}:{eyebrow:string,title:string,text:string,image?:string}){return <section className={`page-hero ${image?'with-image':''}`}><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{text}</p></div>{image&&<img src={image.startsWith('/')?image:`/images/${image}.webp`} alt={`${title} application`}/>}</section>;}
