'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {markets,products,materials,expertise,solutions} from '../lib/catalog';
import {productVisual} from '../lib/content';

export function Icon({kind='box',className=''}:{kind?:string,className?:string}) {
 const paths:Record<string,string>={wind:'M3 8h12a3 3 0 1 0-3-3M2 12h17a3 3 0 1 1-3 3M4 16h5',car:'M3 15V9l3-4h9l4 4h2v6M3 15h18M7 18a2 2 0 1 0 0-4 2 2 0 0 0 0 4m10 0a2 2 0 1 0 0-4 2 2 0 0 0 0 4M6 9h10',factory:'M3 21V7h4v6l5-3v3l5-3v11H3Zm14-11V3h4v18M6 17h1m4 0h1m4 0h1',food:'M3 4v5c0 2 6 2 6 0V4M6 4v17M17 4c-5 4-5 9 0 9h2V4m0 9v8',waves:'M2 6q3-3 6 0t6 0 6 0M2 12q3-3 6 0t6 0 6 0M2 18q3-3 6 0t6 0 6 0',book:'M3 4h6l3 2 3-2h6v16h-6l-3 2-3-2H3V4Zm9 2v16',box:'M3 7l9-5 9 5v10l-9 5-9-5V7zm0 0l9 5 9-5M12 12v10M7 4l10 5',leaf:'M20 3C8 2 3 7 4 14c1 6 8 8 12 3 3-4 4-9 4-14ZM5 19L16 8',arrow:'M4 12h16m-6-6 6 6-6 6',search:'M16 16l5 5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',layers:'m2 7 10-5 10 5-10 5L2 7Zm0 5 10 5 10-5M2 17l10 5 10-5',shield:'m12 2 9 4v6c0 5-9 10-9 10S3 17 3 12V6l9-4Zm-5 10 3 3 7-7',snow:'M12 2v20M3 7l18 10M3 17 21 7M9 4l3 3 3-3M9 20l3-3 3 3',close:'M5 5l14 14M19 5 5 19',play:'m8 4 13 8-13 8V4Z',pause:'M8 4v16M16 4v16',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',menu:'M3 6h18M3 12h18M3 18h18',check:'m4 12 5 5L20 6'};
 return <svg className={className} width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[kind]||paths.box}/></svg>;
}
export function Catalogue({compact=false}:{compact?:boolean}){const [q,setQ]=useState(''),[market,setMarket]=useState('All markets'),[material,setMaterial]=useState('All materials');const filtered=products.filter(p=>(market==='All markets'||p.market===market)&&(material==='All materials'||p.material.split(' / ').includes(material))&&`${p.name} ${p.material} ${p.market}`.toLowerCase().includes(q.toLowerCase()));const result=compact?filtered.slice(0,8):filtered;return <><div className="filters"><label><span>Search products</span><div className="input-icon"><Icon kind="search"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="What are you looking for?"/></div></label><label><span>Market</span><select value={market} onChange={e=>setMarket(e.target.value)}><option>All markets</option>{markets.map(m=><option key={m.slug}>{m.name}</option>)}</select></label><label><span>Material</span><select value={material} onChange={e=>setMaterial(e.target.value)}><option>All materials</option>{['EPP','EPS','PP','PET','PS','Cellular foam'].map(m=><option key={m}>{m}</option>)}</select></label></div><div className="result-meta" aria-live="polite"><span>{filtered.length} product families</span><button onClick={()=>{setQ('');setMarket('All markets');setMaterial('All materials');}}>Reset filters ↺</button></div><div className="product-grid">{result.map(p=><ProductCard key={p.slug} product={p}/>)}</div>{!result.length&&<div className="empty"><h2>No products match those filters.</h2><p>Try a broader search or reset the filters.</p></div>}</>;}
export function ProductCard({product:p}:{product:typeof products[number]}){return <Link href={`/products/${p.slug}/`} className="product-card"><div className={`product-image ${p.image}`}><img src={productVisual(p)} alt={`${p.name} material format`} loading="lazy"/><span className="round-arrow">↗</span></div><div className="product-copy"><span className="eyebrow">{p.market}</span><h3>{p.name}</h3><p>{p.summary}</p><div className="card-bottom"><span>{p.material}</span><span>Explore product →</span></div></div></Link>;}
export function Film(){const [open,setOpen]=useState(false);const dialog=useRef<HTMLDialogElement>(null);useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close();},[open]);return <><button className="film-button" onClick={()=>setOpen(true)}><span><Icon kind="play"/></span>Watch the material story<small>00:12</small></button><dialog ref={dialog} onCancel={()=>setOpen(false)} className="film-dialog"><button className="dialog-close" onClick={()=>setOpen(false)} aria-label="Close film"><Icon kind="close"/></button><h2>A lighter way to think.</h2>{open&&<video controls autoPlay playsInline poster="/images/hero.webp"><source src="/videos/material-story.mp4" type="video/mp4"/><track kind="captions" src="/videos/material-story.vtt" srcLang="en" label="English" default/></video>}<p>Explore protective packaging, engineered components and food packaging concepts.</p></dialog></>;}
export function Enquiry({product=''}:{product?:string}){const [done,setDone]=useState(false);function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const d=new FormData(form);const text=`Parknonwoven EPP — PROJECT ENQUIRY\n\nName: ${d.get('name')}\nEmail: ${d.get('email')}\nCompany: ${d.get('company')}\nProduct: ${d.get('product')}\n\nProject brief:\n${d.get('brief')}\n\nThis is a locally generated enquiry brief. It has not been sent.\n`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='parknonwoven-epp-project-enquiry.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);setDone(true);}return <form onSubmit={submit} className="enquiry"><div className="form-grid"><label>Your name<input name="name" required autoComplete="name"/></label><label>Work email<input name="email" required type="email" autoComplete="email"/></label><label>Company<input name="company" required autoComplete="organization"/></label><label>Product / application<input name="product" defaultValue={product}/></label></div><label>Tell us about your project<textarea name="brief" required rows={5} placeholder="Application, quantities, drawings, dimensions and the challenge you want to solve…"/></label><label className="checkbox"><input type="checkbox" required/>Create a downloadable project brief using these details.</label><button className="button" type="submit">Create enquiry brief <Icon kind="arrow"/></button><p className="form-note">Download your brief, then <a href="mailto:sales@parknonwoven.com">email it to PARK at sales@parknonwoven.com ↗</a>.</p>{done&&<p className="success" role="status"><Icon kind="check"/> Your brief is ready. Check your downloads; it has not been sent.</p>}</form>;}
