'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {markets,products,materials,expertise,solutions} from '../lib/catalog';

export function Icon({kind='box',className=''}:{kind?:string,className?:string}) {
 const paths:Record<string,string>={box:'M3 7l9-5 9 5v10l-9 5-9-5V7zm0 0l9 5 9-5M12 12v10M7 4l10 5',leaf:'M20 3C8 2 3 7 4 14c1 6 8 8 12 3 3-4 4-9 4-14ZM5 19L16 8',arrow:'M4 12h16m-6-6 6 6-6 6',search:'M16 16l5 5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',layers:'m2 7 10-5 10 5-10 5L2 7Zm0 5 10 5 10-5M2 17l10 5 10-5',shield:'m12 2 9 4v6c0 5-9 10-9 10S3 17 3 12V6l9-4Zm-5 10 3 3 7-7',snow:'M12 2v20M3 7l18 10M3 17 21 7M9 4l3 3 3-3M9 20l3-3 3 3',close:'M5 5l14 14M19 5 5 19',play:'m8 4 13 8-13 8V4Z',menu:'M3 6h18M3 12h18M3 18h18',check:'m4 12 5 5L20 6'};
 return <svg className={className} width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[kind]||paths.box}/></svg>;
}
export function Header(){
 const [menu,setMenu]=useState<string|null>(null),[search,setSearch]=useState(false),[q,setQ]=useState(''),[mobile,setMobile]=useState(false);
 const groups:Record<string,{name:string,href:string}[]>={Expertise:expertise.map(x=>({name:x.name,href:`/expertise/${x.slug}/`})),Solutions:solutions.map(x=>({name:x.name,href:`/solutions/${x.slug}/`})),Markets:markets.map(x=>({name:x.name,href:`/markets/${x.slug}/`})),Materials:materials.map(x=>({name:x.name,href:`/materials/${x.slug}/`}))};
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setMenu(null);setSearch(false);setMobile(false);}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[]);
 const found=q.trim()?products.filter(p=>`${p.name} ${p.market} ${p.material}`.toLowerCase().includes(q.toLowerCase())).slice(0,8):[];
 return <><div className="utility"><span>ENGINEERED MATERIALS. CONSIDERED SOLUTIONS.</span><Link href="/resources/">Insights & resources <span>↗</span></Link></div><header><Link href="/" className="logo" onClick={()=>setMenu(null)}><span className="logo-mark">p</span><span>PARKNONWOVEN<small>EPP SOLUTIONS</small></span></Link><nav aria-label="Main navigation" className={mobile?'mobile-open':''}>{Object.keys(groups).map(k=><button key={k} aria-expanded={menu===k} onClick={()=>{setSearch(false);setMenu(menu===k?null:k);}}>{k}<span className="chevron">⌄</span></button>)}<Link href="/products/" onClick={()=>{setMobile(false);setMenu(null);}}>Products</Link><Link href="/about/" onClick={()=>{setMobile(false);setMenu(null);}}>About us</Link></nav><div className="header-actions"><button className="icon-button" aria-label="Search catalogue" onClick={()=>{setMenu(null);setSearch(!search);}}><Icon kind="search"/></button><Link className="button compact" href="/contact/">Let's talk <Icon kind="arrow"/></Link><button className="icon-button mobile-toggle" aria-label="Toggle navigation" aria-expanded={mobile} onClick={()=>setMobile(!mobile)}><Icon kind={mobile?'close':'menu'}/></button></div></header>{menu&&<div className="mega"><div><p className="eyebrow">EXPLORE {menu.toUpperCase()}</p><h2>{menu==='Markets'?'Built around your industry.':'Better decisions start here.'}</h2><Link href={`/${menu.toLowerCase()}/`} onClick={()=>{setMenu(null);setMobile(false);}}>Explore all {menu.toLowerCase()} →</Link></div><div className="mega-links">{groups[menu].map(x=><Link key={x.name} href={x.href} onClick={()=>{setMenu(null);setMobile(false);}}>{x.name}<span>↗</span></Link>)}</div></div>}{search&&<section className="search-panel" aria-label="Search"><div className="search-input"><Icon kind="search"/><input autoFocus type="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products, industries or materials…" aria-label="Search products"/><button className="icon-button" onClick={()=>setSearch(false)} aria-label="Close search"><Icon kind="close"/></button></div>{q&&<p>{found.length?`${found.length} suggested products`:'No matching products. Try foam, food or insulation.'}</p>}<div className="search-results">{found.map(p=><Link key={p.slug} href={`/products/${p.slug}/`} onClick={()=>setSearch(false)}>{p.name}<small>{p.market} →</small></Link>)}</div><Link href="/products/" onClick={()=>setSearch(false)}>Browse the complete catalogue →</Link></section>}</>;
}
export function Catalogue(){const [q,setQ]=useState(''),[market,setMarket]=useState('All markets'),[material,setMaterial]=useState('All materials');const result=products.filter(p=>(market==='All markets'||p.market===market)&&(material==='All materials'||p.material.includes(material))&&`${p.name} ${p.material} ${p.market}`.toLowerCase().includes(q.toLowerCase()));return <><div className="filters"><label><span>Search products</span><div className="input-icon"><Icon kind="search"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="What are you looking for?"/></div></label><label><span>Market</span><select value={market} onChange={e=>setMarket(e.target.value)}><option>All markets</option>{markets.map(m=><option key={m.slug}>{m.name}</option>)}</select></label><label><span>Material</span><select value={material} onChange={e=>setMaterial(e.target.value)}><option>All materials</option>{['EPP','EPS','PP','PET','PS','Cellular foam'].map(m=><option key={m}>{m}</option>)}</select></label></div><div className="result-meta" aria-live="polite"><span>{result.length} product families</span><button onClick={()=>{setQ('');setMarket('All markets');setMaterial('All materials');}}>Reset filters ↺</button></div><div className="product-grid">{result.map(p=><ProductCard key={p.slug} product={p}/>)}</div>{!result.length&&<div className="empty"><h2>No products match those filters.</h2><p>Try a broader search or reset the filters.</p></div>}</>;}
export function ProductCard({product:p}:{product:typeof products[number]}){return <Link href={`/products/${p.slug}/`} className="product-card"><div className={`product-image ${p.image}`}><img src={`/images/${p.image}.webp`} alt={`Illustrative ${p.image==='food'?'food packaging':p.image==='technical'?'moulded technical components':'protective transport containers'}`} loading="lazy"/><span className="round-arrow">↗</span></div><div className="product-copy"><span className="eyebrow">{p.market}</span><h3>{p.name}</h3><p>{p.summary}</p><div className="card-bottom"><span>{p.material}</span><span>Explore product →</span></div></div></Link>;}
export function Film(){const [open,setOpen]=useState(false);const dialog=useRef<HTMLDialogElement>(null);useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close();},[open]);return <><button className="film-button" onClick={()=>setOpen(true)}><span><Icon kind="play"/></span>Watch the material story<small>00:12</small></button><dialog ref={dialog} onCancel={()=>setOpen(false)} className="film-dialog"><button className="dialog-close" onClick={()=>setOpen(false)} aria-label="Close film"><Icon kind="close"/></button><h2>A lighter way to think.</h2>{open&&<video controls autoPlay playsInline poster="/images/hero.webp"><source src="/videos/material-story.mp4" type="video/mp4"/><track kind="captions" src="/videos/material-story.vtt" srcLang="en" label="English" default/></video>}<p>An original visual study of packaging and engineered materials.</p></dialog></>;}
export function Enquiry({product=''}:{product?:string}){const [done,setDone]=useState(false);function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const d=new FormData(form);const text=`Parknonwoven EPP — PROJECT ENQUIRY\n\nName: ${d.get('name')}\nEmail: ${d.get('email')}\nCompany: ${d.get('company')}\nProduct: ${d.get('product')}\n\nProject brief:\n${d.get('brief')}\n\nThis is a locally generated enquiry brief. It has not been sent.\n`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='parknonwoven-epp-project-enquiry.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);setDone(true);}return <form onSubmit={submit} className="enquiry"><div className="form-grid"><label>Your name<input name="name" required autoComplete="name"/></label><label>Work email<input name="email" required type="email" autoComplete="email"/></label><label>Company<input name="company" required autoComplete="organization"/></label><label>Product / application<input name="product" defaultValue={product}/></label></div><label>Tell us about your project<textarea name="brief" required rows={5} placeholder="Application, quantities, drawings, dimensions and the challenge you want to solve…"/></label><label className="checkbox"><input type="checkbox" required/>I understand this creates a downloadable project brief on my device.</label><button className="button" type="submit">Create enquiry brief <Icon kind="arrow"/></button><p className="form-note">Enquiries are not transmitted. Download your brief to share with your chosen supplier.</p>{done&&<p className="success" role="status"><Icon kind="check"/> Your brief is ready. Check your downloads; it has not been sent.</p>}</form>;}
