import sharp from 'sharp';
import {readdirSync,existsSync,mkdirSync,readFileSync,writeFileSync,statSync} from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
const imageRoot=path.resolve('public/images');const destination=path.join(imageRoot,'optimized');mkdirSync(destination,{recursive:true});
const files=[];
function visit(dir){for(const entry of readdirSync(dir,{withFileTypes:true})){if(entry.name==='optimized')continue;const file=path.join(dir,entry.name);if(entry.isDirectory())visit(file);else if(/\.webp$/i.test(file)||(/\.png$/i.test(file)&&!existsSync(file.replace(/\.png$/i,'.webp'))))files.push(file);}}
visit(imageRoot);sharp.concurrency(2);const manifest={};let cursor=0;
async function worker(){while(cursor<files.length){const file=files[cursor++];const original='/images/'+path.relative(imageRoot,file).replaceAll(path.sep,'/');const buffer=readFileSync(file);const metadata=await sharp(buffer).metadata();const hash=createHash('sha256').update(buffer).update('webp-q82-v1').digest('hex').slice(0,10);const name=path.relative(imageRoot,file).replaceAll(path.sep,'-').replace(/\.[^.]+$/,'');const isProduct=original.includes('/products/');const requested=isProduct?[96,320,640,960]:[320,640,960,1440];const widths=[...new Set(requested.map(width=>Math.min(width,metadata.width)))];const variants=[];
 for(const width of widths){const filename=`${name}-${width}-${hash}.webp`;const target=path.join(destination,filename);if(!existsSync(target))await sharp(buffer).resize({width,withoutEnlargement:true}).webp({quality:82,alphaQuality:100,effort:4,lossless:original.includes('park-nonwoven-logo')}).toFile(target);variants.push({width,src:'/images/optimized/'+filename,bytes:statSync(target).size});}
 const main=variants.find(v=>v.width===Math.min(960,metadata.width)) || variants.at(-1);manifest[original]={src:main.src,width:metadata.width,height:metadata.height,srcSet:variants.map(v=>`${v.src} ${v.width}w`).join(', '),variants,originalBytes:buffer.length};}}
await Promise.all([worker(),worker()]);writeFileSync('src/lib/optimized-images.json',JSON.stringify(manifest,null,2)+'\n');
const products=Object.keys(JSON.parse(readFileSync('src/lib/branded-product-images.json','utf8')));const paths=Object.values(JSON.parse(readFileSync('src/lib/branded-product-images.json','utf8')));const before=paths.reduce((sum,src)=>sum+manifest[src].originalBytes,0),after=paths.reduce((sum,src)=>sum+manifest[src].variants.find(v=>v.width===Math.min(960,manifest[src].width)).bytes,0);writeFileSync('research/image-optimization.json',JSON.stringify({images:files.length,productCount:products.length,productOriginalBytes:before,product960Bytes:after,reductionPercent:Math.round((1-after/before)*100)},null,2));console.log(`${files.length} images optimised; product set ${(before/1048576).toFixed(1)} MB -> ${(after/1048576).toFixed(1)} MB at 960px.`);
