import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdirSync} from 'node:fs';
const browser=await chromium.launch();
const page=await browser.newPage({viewport:{width:1920,height:1080}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
mkdirSync('artifacts',{recursive:true});
await page.goto('http://127.0.0.1:3100/',{waitUntil:'networkidle'});
await page.getByRole('button',{name:/^Our products/}).hover();
await page.locator('.park-menu-links img').first().waitFor();
assert.equal(await page.locator('.park-rail-options button').count(),5);
assert.equal(await page.locator('.park-menu-count').innerText(),`${await page.locator('.park-menu-links a').count()} product families`);
const panel=await page.locator('.park-mega').boundingBox();
assert.ok(panel.width<=1601&&panel.height<650);
assert.ok(await page.locator('.park-mega').evaluate(el=>parseFloat(getComputedStyle(el).borderRadius)>=12));
await page.locator('.park-menu-links a').nth(1).hover();
assert.equal(await page.locator('.park-product-preview h3').innerText(),await page.locator('.park-menu-links a').nth(1).locator('strong').innerText());
await page.locator('.park-menu-links a').nth(2).focus();
assert.equal(await page.locator('.park-product-preview h3').innerText(),await page.locator('.park-menu-links a').nth(2).locator('strong').innerText());
await page.screenshot({path:'artifacts/menu-new-1920.png'});
for(let i=0;i<5;i++){
 await page.locator('.park-rail-options button').nth(i).hover();
 const firstName=await page.locator('.park-menu-links strong').first().innerText();
 assert.equal(await page.locator('.park-product-preview h3').innerText(),firstName);
 assert.ok(await page.locator('.park-menu-links a').count());
 assert.ok(await page.locator('.park-product-preview img').evaluate(img=>img.complete&&img.naturalWidth>0));
}
await page.locator('.park-rail-options button').first().hover();
await page.setViewportSize({width:1440,height:900});
await page.screenshot({path:'artifacts/menu-new-1440.png'});
await page.keyboard.press('Escape');
assert.equal(await page.locator('.park-mega').count(),0);
await page.getByRole('button',{name:/^Our products/}).hover();
await page.locator('.park-menu-links a').nth(1).hover();
await page.locator('.park-product-preview .button').click();
await page.waitForURL('**/products/moulded-air-ducts/');
await page.setViewportSize({width:390,height:844});
await page.goto('http://127.0.0.1:3100/');
await page.getByRole('button',{name:'Toggle navigation'}).click();
await page.getByRole('button',{name:/^Our products/}).click();
await page.locator('.park-rail-options button').nth(2).click();
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.locator('.park-menu-links a').first().scrollIntoViewIfNeeded();
await page.screenshot({path:'artifacts/menu-new-mobile.png'});
await page.locator('.park-menu-links a').first().click();
await page.waitForURL('**/products/meat-packaging/');
assert.equal(await page.locator('.park-mega').count(),0);
assert.deepEqual(errors,[]);
await browser.close();
console.log('Menu checks passed: compact rounded layout, 5 groups, correct thumbnails, hover/focus preview, preview links, mobile navigation, Escape and no overflow.');
