import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const origin='http://127.0.0.1:3100';
mkdirSync('artifacts',{recursive:true});
await page.goto(origin,{waitUntil:'networkidle'});
assert.equal(await page.locator('h1').count(),1);
assert.equal(await page.locator('img').evaluateAll(imgs=>imgs.filter(i=>i.loading!=='lazy'&&(!i.complete||!i.naturalWidth)).length),0);
await page.screenshot({path:'artifacts/home-desktop.png',fullPage:false});
await page.getByRole('button',{name:/^Markets/}).hover();
assert.equal(await page.locator('.park-rail-options button').count(),13);
await page.locator('.park-view-all').click();
await page.waitForURL('**/markets/');
assert.ok((await page.locator('h1').innerText()).includes('industries'));
await page.goto(origin+'/products/');
const total=await page.locator('.product-card').count();assert.ok(total>60);
await page.locator('.filters select').first().selectOption('Agrifood');
assert.ok((await page.locator('.product-card').count())<total);
await page.locator('.filters input').fill('Compartment');
assert.equal(await page.locator('.product-card').count(),1);
await page.locator('.product-card').click();
await page.waitForURL('**/products/compartment-meal-trays/');
await page.locator('.enquiry input[name="name"]').fill('Test Buyer');
await page.locator('.enquiry input[name="email"]').fill('buyer@example.com');
await page.locator('.enquiry input[name="company"]').fill('Test Company');
await page.locator('.enquiry textarea').fill('Evaluate sample dimensions for a meal packaging application.');
await page.locator('.enquiry input[type="checkbox"]').check();
const downloadPromise=page.waitForEvent('download');
await page.getByRole('button',{name:'Create enquiry brief'}).click();
const download=await downloadPromise;assert.equal(download.suggestedFilename(),'parknonwoven-epp-project-enquiry.txt');
assert.ok((await page.locator('[role="status"]').innerText()).includes('not been sent'));
await page.goto(origin);
await page.getByRole('button',{name:'Watch the material story'}).click();
await page.waitForFunction(()=>{const v=document.querySelector('.film-dialog video');return v&&v.readyState>=2;});
assert.ok(await page.locator('.film-dialog video').evaluate(v=>v.duration>=11.9&&v.duration<=12.1));
await page.getByRole('button',{name:'Close film'}).click();
await page.getByRole('button',{name:'Search catalogue'}).click();
await page.getByRole('searchbox',{name:'Search products'}).fill('HVAC');
assert.ok((await page.locator('.search-results a').count())>0);
await page.keyboard.press('Escape');
await page.setViewportSize({width:390,height:844});
await page.goto(origin,{waitUntil:'networkidle'});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
await page.screenshot({path:'artifacts/home-mobile.png',fullPage:false});
await page.getByRole('button',{name:'Toggle navigation'}).click();
await page.locator('header nav').getByRole('button',{name:'Our products',exact:false}).click();
await page.locator('.park-view-all').click();
await page.waitForURL('**/products/');
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
await page.screenshot({path:'artifacts/catalogue-mobile.png',fullPage:true});
assert.deepEqual(errors,[]);
writeFileSync('artifacts/browser-check.json',JSON.stringify({passed:true,productFamilies:total,checks:['Desktop and mobile rendering','No broken images or JavaScript errors','Mega-menu navigation','Market filters and product search','Product details','Enquiry download','Video playback and captions','Global search','Mobile navigation','No mobile horizontal overflow']},null,2));
console.log(`Browser checks passed: ${total} product families, desktop and mobile.`);
await browser.close();
